-- =====================================================
-- CRUMBEAR CAKE MANAGEMENT SYSTEM - CUSTOMER SEED DATA
-- 500 Customer Records
-- Distribution:
--   - 40% Pet-like/Nickname names (~200)
--   - 60% Filipino names (~300)
--   - 85% Zamboanga City (~425)
--   - 15% Other Philippine cities (~75)
-- =====================================================

USE CrumbearDB;
GO

-- Clear existing data
DELETE FROM Reviews;
DELETE FROM Customers;
GO

-- Reset identity
DBCC CHECKIDENT ('Customers', RESEED, 0);
GO

INSERT INTO Customers (full_name, email, city) VALUES
-- Pet-like/Nickname Names - Zamboanga City (170 records: 1-170)
('Bubbles Reyes', 'bubbles.reyes@gmail.com', 'Zamboanga City'),
('Bubby Santos', 'bubby.santos@yahoo.com', 'Zamboanga City'),
('Bella Cruz', 'bella.cruz@gmail.com', 'Zamboanga City'),
('Peanut Mendoza', 'peanut.mendoza@outlook.com', 'Zamboanga City'),
('Mochi Garcia', 'mochi.garcia@gmail.com', 'Zamboanga City'),
('Bear Fernandez', 'bear.fernandez@yahoo.com', 'Zamboanga City'),
('Cookie Torres', 'cookie.torres@gmail.com', 'Zamboanga City'),
('Cupcake Ramos', 'cupcake.ramos@outlook.com', 'Zamboanga City'),
('Sprinkles Dela Cruz', 'sprinkles.delacruz@gmail.com', 'Zamboanga City'),
('Cinnamon Villanueva', 'cinnamon.villanueva@yahoo.com', 'Zamboanga City'),
('Honey Aquino', 'honey.aquino@gmail.com', 'Zamboanga City'),
('Sugar Tan', 'sugar.tan@outlook.com', 'Zamboanga City'),
('Candy Lopez', 'candy.lopez@gmail.com', 'Zamboanga City'),
('Gummy Lim', 'gummy.lim@yahoo.com', 'Zamboanga City'),
('Caramel Ong', 'caramel.ong@gmail.com', 'Zamboanga City'),
('Pudding Sy', 'pudding.sy@outlook.com', 'Zamboanga City'),
('Brownie Chua', 'brownie.chua@gmail.com', 'Zamboanga City'),
('Biscuit Ang', 'biscuit.ang@yahoo.com', 'Zamboanga City'),
('Waffle Co', 'waffle.co@gmail.com', 'Zamboanga City'),
('Pancake Dy', 'pancake.dy@outlook.com', 'Zamboanga City'),
('Toffee Yap', 'toffee.yap@gmail.com', 'Zamboanga City'),
('Jellybean Tam', 'jellybean.tam@yahoo.com', 'Zamboanga City'),
('Twinkle Chung', 'twinkle.chung@gmail.com', 'Zamboanga City'),
('Sparkle Lee', 'sparkle.lee@outlook.com', 'Zamboanga City'),
('Glitter Wu', 'glitter.wu@gmail.com', 'Zamboanga City'),
('Sunny Chan', 'sunny.chan@yahoo.com', 'Zamboanga City'),
('Rainbow Tiu', 'rainbow.tiu@gmail.com', 'Zamboanga City'),
('Starlight Uy', 'starlight.uy@outlook.com', 'Zamboanga City'),
('Moonbeam Yu', 'moonbeam.yu@gmail.com', 'Zamboanga City'),
('Buttercup Ngo', 'buttercup.ngo@yahoo.com', 'Zamboanga City'),
('Daisy Bautista', 'daisy.bautista@gmail.com', 'Zamboanga City'),
('Lily Pascual', 'lily.pascual@outlook.com', 'Zamboanga City'),
('Rose Santiago', 'rose.santiago@gmail.com', 'Zamboanga City'),
('Violet Rivera', 'violet.rivera@yahoo.com', 'Zamboanga City'),
('Poppy Castro', 'poppy.castro@gmail.com', 'Zamboanga City'),
('Tulip Dimaculangan', 'tulip.dimaculangan@outlook.com', 'Zamboanga City'),
('Petunia Manalo', 'petunia.manalo@gmail.com', 'Zamboanga City'),
('Daffodil Soriano', 'daffodil.soriano@yahoo.com', 'Zamboanga City'),
('Clover Mercado', 'clover.mercado@gmail.com', 'Zamboanga City'),
('Fern Navarro', 'fern.navarro@outlook.com', 'Zamboanga City'),
('Willow Jimenez', 'willow.jimenez@gmail.com', 'Zamboanga City'),
('Ivy Peralta', 'ivy.peralta@yahoo.com', 'Zamboanga City'),
('Holly Medina', 'holly.medina@gmail.com', 'Zamboanga City'),
('Jasmine Aguilar', 'jasmine.aguilar@outlook.com', 'Zamboanga City'),
('Orchid Flores', 'orchid.flores@gmail.com', 'Zamboanga City'),
('Peaches Domingo', 'peaches.domingo@yahoo.com', 'Zamboanga City'),
('Cherry Salazar', 'cherry.salazar@gmail.com', 'Zamboanga City'),
('Berry Luna', 'berry.luna@outlook.com', 'Zamboanga City'),
('Apple Espinosa', 'apple.espinosa@gmail.com', 'Zamboanga City'),
('Kiwi Magno', 'kiwi.magno@yahoo.com', 'Zamboanga City'),
('Mango Hernandez', 'mango.hernandez@gmail.com', 'Zamboanga City'),
('Papaya Valdez', 'papaya.valdez@outlook.com', 'Zamboanga City'),
('Coco Ocampo', 'coco.ocampo@gmail.com', 'Zamboanga City'),
('Mocha Robles', 'mocha.robles@yahoo.com', 'Zamboanga City'),
('Latte Castillo', 'latte.castillo@gmail.com', 'Zamboanga City'),
('Espresso Morales', 'espresso.morales@outlook.com', 'Zamboanga City'),
('Cappuccino Ignacio', 'cappuccino.ignacio@gmail.com', 'Zamboanga City'),
('Frappe Tolentino', 'frappe.tolentino@yahoo.com', 'Zamboanga City'),
('Chai Sebastian', 'chai.sebastian@gmail.com', 'Zamboanga City'),
('Matcha Velasco', 'matcha.velasco@outlook.com', 'Zamboanga City'),
('Boba Marquez', 'boba.marquez@gmail.com', 'Zamboanga City'),
('Tapioca Salvador', 'tapioca.salvador@yahoo.com', 'Zamboanga City'),
('Noodle Padilla', 'noodle.padilla@gmail.com', 'Zamboanga City'),
('Dumpling Miranda', 'dumpling.miranda@outlook.com', 'Zamboanga City'),
('Dimsum Gutierrez', 'dimsum.gutierrez@gmail.com', 'Zamboanga City'),
('Sushi Magsaysay', 'sushi.magsaysay@yahoo.com', 'Zamboanga City'),
('Tempura Franco', 'tempura.franco@gmail.com', 'Zamboanga City'),
('Ramen Sarmiento', 'ramen.sarmiento@outlook.com', 'Zamboanga City'),
('Tofu Perez', 'tofu.perez@gmail.com', 'Zamboanga City'),
('Kimchi Rosales', 'kimchi.rosales@yahoo.com', 'Zamboanga City'),
('Pebbles Abella', 'pebbles.abella@gmail.com', 'Zamboanga City'),
('Bambi Buenaventura', 'bambi.buenaventura@outlook.com', 'Zamboanga City'),
('Bambo Concepcion', 'bambo.concepcion@gmail.com', 'Zamboanga City'),
('Buttons Delgado', 'buttons.delgado@yahoo.com', 'Zamboanga City'),
('Cuddles Enriquez', 'cuddles.enriquez@gmail.com', 'Zamboanga City'),
('Doodles Fajardo', 'doodles.fajardo@outlook.com', 'Zamboanga City'),
('Fluffy Galang', 'fluffy.galang@gmail.com', 'Zamboanga City'),
('Fuzzy Hidalgo', 'fuzzy.hidalgo@yahoo.com', 'Zamboanga City'),
('Giggles Imperial', 'giggles.imperial@gmail.com', 'Zamboanga City'),
('Huggy Jacinto', 'huggy.jacinto@outlook.com', 'Zamboanga City'),
('Kisses Kapunan', 'kisses.kapunan@gmail.com', 'Zamboanga City'),
('Lollipop Lacson', 'lollipop.lacson@yahoo.com', 'Zamboanga City'),
('Marshmallow Macapagal', 'marshmallow.macapagal@gmail.com', 'Zamboanga City'),
('Nugget Nakpil', 'nugget.nakpil@outlook.com', 'Zamboanga City'),
('Oreo Ongpin', 'oreo.ongpin@gmail.com', 'Zamboanga City'),
('Paws Palma', 'paws.palma@yahoo.com', 'Zamboanga City'),
('Puff Quijano', 'puff.quijano@gmail.com', 'Zamboanga City'),
('Ruffles Razon', 'ruffles.razon@outlook.com', 'Zamboanga City'),
('Snuggles Sotto', 'snuggles.sotto@gmail.com', 'Zamboanga City'),
('Taffy Tanco', 'taffy.tanco@yahoo.com', 'Zamboanga City'),
('Tickles Ubaldo', 'tickles.ubaldo@gmail.com', 'Zamboanga City'),
('Waffles Vargas', 'waffles.vargas@outlook.com', 'Zamboanga City'),
('Whiskers Yulo', 'whiskers.yulo@gmail.com', 'Zamboanga City'),
('Zippy Zamora', 'zippy.zamora@yahoo.com', 'Zamboanga City'),
('Bubba Abaya', 'bubba.abaya@gmail.com', 'Zamboanga City'),
('Chubby Bacani', 'chubby.bacani@outlook.com', 'Zamboanga City'),
('Dizzy Cabrera', 'dizzy.cabrera@gmail.com', 'Zamboanga City'),
('Fizzy Dalisay', 'fizzy.dalisay@yahoo.com', 'Zamboanga City'),
('Jazzy Escoda', 'jazzy.escoda@gmail.com', 'Zamboanga City'),
('Misty Fontanilla', 'misty.fontanilla@outlook.com', 'Zamboanga City'),
('Peppy Gonzaga', 'peppy.gonzaga@gmail.com', 'Zamboanga City'),
('Pippy Halili', 'pippy.halili@yahoo.com', 'Zamboanga City'),
('Skippy Ilagan', 'skippy.ilagan@gmail.com', 'Zamboanga City'),
('Snappy Javier', 'snappy.javier@outlook.com', 'Zamboanga City'),
('Speedy Katigbak', 'speedy.katigbak@gmail.com', 'Zamboanga City'),
('Squeaky Laurel', 'squeaky.laurel@yahoo.com', 'Zamboanga City'),
('Sticky Madrigal', 'sticky.madrigal@gmail.com', 'Zamboanga City'),
('Stretchy Natividad', 'stretchy.natividad@outlook.com', 'Zamboanga City'),
('Swirly Osmena', 'swirly.osmena@gmail.com', 'Zamboanga City'),
('Twinkie Pangilinan', 'twinkie.pangilinan@yahoo.com', 'Zamboanga City'),
('Wiggly Quezon', 'wiggly.quezon@gmail.com', 'Zamboanga City'),
('Zigzag Recto', 'zigzag.recto@outlook.com', 'Zamboanga City'),
('Binky Sison', 'binky.sison@gmail.com', 'Zamboanga City'),
('Blinky Tantoco', 'blinky.tantoco@yahoo.com', 'Zamboanga City'),
('Bouncy Urquiola', 'bouncy.urquiola@gmail.com', 'Zamboanga City'),
('Bubbly Villamor', 'bubbly.villamor@outlook.com', 'Zamboanga City'),
('Chewy Wenceslao', 'chewy.wenceslao@gmail.com', 'Zamboanga City'),
('Crispy Yabut', 'crispy.yabut@yahoo.com', 'Zamboanga City'),
('Crunchy Zobel', 'crunchy.zobel@gmail.com', 'Zamboanga City'),
('Dreamy Aglipay', 'dreamy.aglipay@outlook.com', 'Zamboanga City'),
('Frosty Bonifacio', 'frosty.bonifacio@gmail.com', 'Zamboanga City'),
('Gooey Cojuangco', 'gooey.cojuangco@yahoo.com', 'Zamboanga City'),
('Icy Diokno', 'icy.diokno@gmail.com', 'Zamboanga City'),
('Jiggly Escudero', 'jiggly.escudero@outlook.com', 'Zamboanga City'),
('Melty Feliciano', 'melty.feliciano@gmail.com', 'Zamboanga City'),
('Minty Gorospe', 'minty.gorospe@yahoo.com', 'Zamboanga City'),
('Peachy Herrera', 'peachy.herrera@gmail.com', 'Zamboanga City'),
('Perky Inting', 'perky.inting@outlook.com', 'Zamboanga City'),
('Plucky Jocson', 'plucky.jocson@gmail.com', 'Zamboanga City'),
('Salty Kalaw', 'salty.kalaw@yahoo.com', 'Zamboanga City'),
('Silky Lorenzo', 'silky.lorenzo@gmail.com', 'Zamboanga City'),
('Smoky Macaraig', 'smoky.macaraig@outlook.com', 'Zamboanga City'),
('Spicy Nepomuceno', 'spicy.nepomuceno@gmail.com', 'Zamboanga City'),
('Sugary Olivares', 'sugary.olivares@yahoo.com', 'Zamboanga City'),
('Sweet Pimentel', 'sweet.pimentel@gmail.com', 'Zamboanga City'),
('Tangy Quintos', 'tangy.quintos@outlook.com', 'Zamboanga City'),
('Toasty Romualdez', 'toasty.romualdez@gmail.com', 'Zamboanga City'),
('Twisty Salonga', 'twisty.salonga@yahoo.com', 'Zamboanga City'),
('Velvety Trinidad', 'velvety.trinidad@gmail.com', 'Zamboanga City'),
('Zesty Ungson', 'zesty.ungson@outlook.com', 'Zamboanga City'),
('Breezy Valera', 'breezy.valera@gmail.com', 'Zamboanga City'),
('Cozy Wenceslao', 'cozy.wenceslao@yahoo.com', 'Zamboanga City'),
('Hazy Ysip', 'hazy.ysip@gmail.com', 'Zamboanga City'),
('Lazy Zarate', 'lazy.zarate@outlook.com', 'Zamboanga City'),
('Snoozy Abad', 'snoozy.abad@gmail.com', 'Zamboanga City'),
('Drowsy Bello', 'drowsy.bello@yahoo.com', 'Zamboanga City'),
('Sleepy Cariño', 'sleepy.carino@gmail.com', 'Zamboanga City'),
('Yawny Dacquel', 'yawny.dacquel@outlook.com', 'Zamboanga City'),
('Snooze Evidente', 'snooze.evidente@gmail.com', 'Zamboanga City'),
('Nappy Faustino', 'nappy.faustino@yahoo.com', 'Zamboanga City'),
('Dreamz Gatchalian', 'dreamz.gatchalian@gmail.com', 'Zamboanga City'),
('Cloudy Hontiveros', 'cloudy.hontiveros@outlook.com', 'Zamboanga City'),
('Puffy Inchausti', 'puffy.inchausti@gmail.com', 'Zamboanga City'),
('Softy Jalandoni', 'softy.jalandoni@yahoo.com', 'Zamboanga City'),
('Cushy Kasilag', 'cushy.kasilag@gmail.com', 'Zamboanga City'),
('Squishy Legarda', 'squishy.legarda@outlook.com', 'Zamboanga City'),
('Comfy Maceda', 'comfy.maceda@gmail.com', 'Zamboanga City'),
('Snug Nakpil', 'snug.nakpil@yahoo.com', 'Zamboanga City'),
('Cocobean Ongpin', 'cocobean.ongpin@gmail.com', 'Zamboanga City'),
('Beanie Palanca', 'beanie.palanca@outlook.com', 'Zamboanga City'),
('Muffin Quimpo', 'muffin.quimpo@gmail.com', 'Zamboanga City'),
('Pretzel Reyes', 'pretzel.reyes@yahoo.com', 'Zamboanga City'),
('Crumb Syjuco', 'crumb.syjuco@gmail.com', 'Zamboanga City'),
('Loaf Tuason', 'loaf.tuason@outlook.com', 'Zamboanga City'),
('Bun Urrutia', 'bun.urrutia@gmail.com', 'Zamboanga City'),
('Roll Villanueva', 'roll.villanueva@yahoo.com', 'Zamboanga City'),

-- Pet-like/Nickname Names - Other Philippine Cities (30 records: 171-200)
('Butterbean Abellana', 'butterbean.abellana@gmail.com', 'Cebu City'),
('Honeybun Bohol', 'honeybun.bohol@outlook.com', 'Davao City'),
('Sweetpea Calamba', 'sweetpea.calamba@gmail.com', 'Manila'),
('Lovebug Dumaguete', 'lovebug.dumaguete@yahoo.com', 'Quezon City'),
('Snickerdoodle Estrada', 'snickerdoodle.estrada@gmail.com', 'Makati'),
('Cuddlebug Fernando', 'cuddlebug.fernando@outlook.com', 'Pasig'),
('Teddybear Gomez', 'teddybear.gomez@gmail.com', 'Taguig'),
('Sugarplum Habagat', 'sugarplum.habagat@yahoo.com', 'Iloilo City'),
('Honeycomb Ibarra', 'honeycomb.ibarra@gmail.com', 'Bacolod'),
('Buttermilk Jacinto', 'buttermilk.jacinto@outlook.com', 'Cagayan de Oro'),
('Gingerbread Kiko', 'gingerbread.kiko@gmail.com', 'General Santos'),
('Snowflake Laguna', 'snowflake.laguna@yahoo.com', 'Baguio'),
('Stardust Makati', 'stardust.makati@gmail.com', 'Cebu City'),
('Moonpie Naga', 'moonpie.naga@outlook.com', 'Davao City'),
('Sunflower Olongapo', 'sunflower.olongapo@gmail.com', 'Angeles City'),
('Raindrop Pangasinan', 'raindrop.pangasinan@yahoo.com', 'San Fernando'),
('Snowball Quezon', 'snowball.quezon@gmail.com', 'Lipa'),
('Sunshine Rizal', 'sunshine.rizal@outlook.com', 'Batangas City'),
('Starshine Santos', 'starshine.santos@gmail.com', 'Lucena'),
('Moonshine Tagaytay', 'moonshine.tagaytay@yahoo.com', 'Tagaytay'),
('Dewdrop Urdaneta', 'dewdrop.urdaneta@gmail.com', 'Dagupan'),
('Raindance Vigan', 'raindance.vigan@outlook.com', 'Vigan'),
('Sunbeam Wawa', 'sunbeam.wawa@gmail.com', 'Antipolo'),
('Starlight Xiong', 'starlight.xiong@yahoo.com', 'Caloocan'),
('Glimmer Yusop', 'glimmer.yusop@gmail.com', 'Parañaque'),
('Shimmer Zapata', 'shimmer.zapata@outlook.com', 'Las Piñas'),
('Twirl Araneta', 'twirl.araneta@gmail.com', 'Mandaluyong'),
('Swirl Binay', 'swirl.binay@yahoo.com', 'San Juan'),
('Curly Calixto', 'curly.calixto@gmail.com', 'Marikina'),
('Whirl Dizon', 'whirl.dizon@outlook.com', 'Valenzuela'),

-- Filipino Names - Zamboanga City (255 records: 201-455)
('Maria Clara Reyes', 'mariaclara.reyes@gmail.com', 'Zamboanga City'),
('Jose Rizal Santos', 'joserizal.santos@yahoo.com', 'Zamboanga City'),
('Andres Bonifacio Cruz', 'andresbonifacio.cruz@gmail.com', 'Zamboanga City'),
('Emilio Aguinaldo Mendoza', 'emilioaguinaldo.mendoza@outlook.com', 'Zamboanga City'),
('Gabriela Silang Garcia', 'gabrielasilang.garcia@gmail.com', 'Zamboanga City'),
('Juan Luna Fernandez', 'juanluna.fernandez@yahoo.com', 'Zamboanga City'),
('Apolinario Mabini Torres', 'apolinariomabini.torres@gmail.com', 'Zamboanga City'),
('Melchora Aquino Ramos', 'melchoraaquino.ramos@outlook.com', 'Zamboanga City'),
('Antonio Luna Dela Cruz', 'antonioluna.delacruz@gmail.com', 'Zamboanga City'),
('Gregorio Del Pilar Villanueva', 'gregoriodelpilar.villanueva@yahoo.com', 'Zamboanga City'),
('Mariano Ponce Aquino', 'marianoponce.aquino@gmail.com', 'Zamboanga City'),
('Trinidad Tecson Tan', 'trinidadtecson.tan@outlook.com', 'Zamboanga City'),
('Diego Silang Lopez', 'diegosilang.lopez@gmail.com', 'Zamboanga City'),
('Leonor Rivera Lim', 'leonorrivera.lim@yahoo.com', 'Zamboanga City'),
('Paciano Rizal Ong', 'pacianoRizal.ong@gmail.com', 'Zamboanga City'),
('Narcisa Rizal Sy', 'narcisarizal.sy@outlook.com', 'Zamboanga City'),
('Lorenzo Ruiz Chua', 'lorenzoruiz.chua@gmail.com', 'Zamboanga City'),
('Pedro Calungsod Ang', 'pedrocalungsod.ang@yahoo.com', 'Zamboanga City'),
('Corazon Aquino Co', 'corazonaquino.co@gmail.com', 'Zamboanga City'),
('Benigno Aquino Dy', 'benignoaquino.dy@outlook.com', 'Zamboanga City'),
('Lourdes Bautista', 'lourdes.bautista88@gmail.com', 'Zamboanga City'),
('Milagros Pascual', 'milagros.pascual77@yahoo.com', 'Zamboanga City'),
('Esperanza Santiago', 'esperanza.santiago66@gmail.com', 'Zamboanga City'),
('Concepcion Rivera', 'concepcion.rivera55@outlook.com', 'Zamboanga City'),
('Remedios Castro', 'remedios.castro44@gmail.com', 'Zamboanga City'),
('Purificacion Dimaculangan', 'purificacion.dimaculangan@yahoo.com', 'Zamboanga City'),
('Encarnacion Manalo', 'encarnacion.manalo@gmail.com', 'Zamboanga City'),
('Asuncion Soriano', 'asuncion.soriano@outlook.com', 'Zamboanga City'),
('Presentacion Mercado', 'presentacion.mercado@gmail.com', 'Zamboanga City'),
('Resurreccion Navarro', 'resurreccion.navarro@yahoo.com', 'Zamboanga City'),
('Natividad Jimenez', 'natividad.jimenez@gmail.com', 'Zamboanga City'),
('Trinidad Peralta', 'trinidad.peralta@outlook.com', 'Zamboanga City'),
('Soledad Medina', 'soledad.medina@gmail.com', 'Zamboanga City'),
('Caridad Aguilar', 'caridad.aguilar@yahoo.com', 'Zamboanga City'),
('Piedad Flores', 'piedad.flores@gmail.com', 'Zamboanga City'),
('Fe Domingo', 'fe.domingo@outlook.com', 'Zamboanga City'),
('Amor Salazar', 'amor.salazar@gmail.com', 'Zamboanga City'),
('Luz Luna', 'luz.luna@yahoo.com', 'Zamboanga City'),
('Paz Espinosa', 'paz.espinosa@gmail.com', 'Zamboanga City'),
('Gracia Magno', 'gracia.magno@outlook.com', 'Zamboanga City'),
('Merced Hernandez', 'merced.hernandez@gmail.com', 'Zamboanga City'),
('Pilar Valdez', 'pilar.valdez@yahoo.com', 'Zamboanga City'),
('Rosario Ocampo', 'rosario.ocampo@gmail.com', 'Zamboanga City'),
('Carmen Robles', 'carmen.robles@outlook.com', 'Zamboanga City'),
('Dolores Castillo', 'dolores.castillo@gmail.com', 'Zamboanga City'),
('Angeles Morales', 'angeles.morales@yahoo.com', 'Zamboanga City'),
('Nieves Ignacio', 'nieves.ignacio@gmail.com', 'Zamboanga City'),
('Consuelo Tolentino', 'consuelo.tolentino@outlook.com', 'Zamboanga City'),
('Socorro Sebastian', 'socorro.sebastian@gmail.com', 'Zamboanga City'),
('Amparo Velasco', 'amparo.velasco@yahoo.com', 'Zamboanga City'),
('Roberto Marquez', 'roberto.marquez@gmail.com', 'Zamboanga City'),
('Eduardo Salvador', 'eduardo.salvador@outlook.com', 'Zamboanga City'),
('Ricardo Padilla', 'ricardo.padilla@gmail.com', 'Zamboanga City'),
('Fernando Miranda', 'fernando.miranda@yahoo.com', 'Zamboanga City'),
('Alejandro Gutierrez', 'alejandro.gutierrez@gmail.com', 'Zamboanga City'),
('Alfredo Magsaysay', 'alfredo.magsaysay@outlook.com', 'Zamboanga City'),
('Ernesto Franco', 'ernesto.franco@gmail.com', 'Zamboanga City'),
('Leonardo Sarmiento', 'leonardo.sarmiento@yahoo.com', 'Zamboanga City'),
('Armando Perez', 'armando.perez@gmail.com', 'Zamboanga City'),
('Rodolfo Rosales', 'rodolfo.rosales@outlook.com', 'Zamboanga City'),
('Rolando Abella', 'rolando.abella@gmail.com', 'Zamboanga City'),
('Orlando Buenaventura', 'orlando.buenaventura@yahoo.com', 'Zamboanga City'),
('Reynaldo Concepcion', 'reynaldo.concepcion@gmail.com', 'Zamboanga City'),
('Danilo Delgado', 'danilo.delgado@outlook.com', 'Zamboanga City'),
('Renato Enriquez', 'renato.enriquez@gmail.com', 'Zamboanga City'),
('Edilberto Fajardo', 'edilberto.fajardo@yahoo.com', 'Zamboanga City'),
('Virgilio Galang', 'virgilio.galang@gmail.com', 'Zamboanga City'),
('Teofilo Hidalgo', 'teofilo.hidalgo@outlook.com', 'Zamboanga City'),
('Crisanto Imperial', 'crisanto.imperial@gmail.com', 'Zamboanga City'),
('Feliciano Jacinto', 'feliciano.jacinto@yahoo.com', 'Zamboanga City'),
('Marcelo Kapunan', 'marcelo.kapunan@gmail.com', 'Zamboanga City'),
('Remigio Lacson', 'remigio.lacson@outlook.com', 'Zamboanga City'),
('Telesforo Macapagal', 'telesforo.macapagal@gmail.com', 'Zamboanga City'),
('Hermogenes Nakpil', 'hermogenes.nakpil@yahoo.com', 'Zamboanga City'),
('Simplicio Ongpin', 'simplicio.ongpin@gmail.com', 'Zamboanga City'),
('Epifanio Palma', 'epifanio.palma@outlook.com', 'Zamboanga City'),
('Anastacio Quijano', 'anastacio.quijano@gmail.com', 'Zamboanga City'),
('Cornelio Razon', 'cornelio.razon@yahoo.com', 'Zamboanga City'),
('Demetrio Sotto', 'demetrio.sotto@gmail.com', 'Zamboanga City'),
('Faustino Tanco', 'faustino.tanco@outlook.com', 'Zamboanga City'),
('Gelasio Ubaldo', 'gelasio.ubaldo@gmail.com', 'Zamboanga City'),
('Hilario Vargas', 'hilario.vargas@yahoo.com', 'Zamboanga City'),
('Isidro Yulo', 'isidro.yulo@gmail.com', 'Zamboanga City'),
('Jacinto Zamora', 'jacinto.zamora@outlook.com', 'Zamboanga City'),
('Kristine Mae Abaya', 'kristinemae.abaya@gmail.com', 'Zamboanga City'),
('Lovely Joy Bacani', 'lovelyjoy.bacani@yahoo.com', 'Zamboanga City'),
('Princess Anne Cabrera', 'princessanne.cabrera@gmail.com', 'Zamboanga City'),
('Mary Grace Dalisay', 'marygrace.dalisay@outlook.com', 'Zamboanga City'),
('Angel Rose Escoda', 'angelrose.escoda@gmail.com', 'Zamboanga City'),
('Cherry Mae Fontanilla', 'cherrymae.fontanilla@yahoo.com', 'Zamboanga City'),
('Divine Grace Gonzaga', 'divinegrace.gonzaga@gmail.com', 'Zamboanga City'),
('Precious Joy Halili', 'preciousjoy.halili@outlook.com', 'Zamboanga City'),
('Heaven Leigh Ilagan', 'heavenleigh.ilagan@gmail.com', 'Zamboanga City'),
('Faith Hope Javier', 'faithhope.javier@yahoo.com', 'Zamboanga City'),
('Charity Love Katigbak', 'charitylove.katigbak@gmail.com', 'Zamboanga City'),
('Blessing Joy Laurel', 'blessingjoy.laurel@outlook.com', 'Zamboanga City'),
('Miracle Grace Madrigal', 'miraclegrace.madrigal@gmail.com', 'Zamboanga City'),
('Destiny Hope Natividad', 'destinyhope.natividad@yahoo.com', 'Zamboanga City'),
('Serenity Mae Osmena', 'serenitymae.osmena@gmail.com', 'Zamboanga City'),
('Harmony Joy Pangilinan', 'harmonyjoy.pangilinan@outlook.com', 'Zamboanga City'),
('Melody Grace Quezon', 'melodygrace.quezon@gmail.com', 'Zamboanga City'),
('Symphony Love Recto', 'symphonylove.recto@yahoo.com', 'Zamboanga City'),
('Rhapsody Joy Sison', 'rhapsodyjoy.sison@gmail.com', 'Zamboanga City'),
('Sonata Mae Tantoco', 'sonatamae.tantoco@outlook.com', 'Zamboanga City'),
('John Paul Urquiola', 'johnpaul.urquiola@gmail.com', 'Zamboanga City'),
('Mark Anthony Villamor', 'markanthony.villamor@yahoo.com', 'Zamboanga City'),
('James Michael Wenceslao', 'jamesmichael.wenceslao@gmail.com', 'Zamboanga City'),
('David Joshua Yabut', 'davidjoshua.yabut@outlook.com', 'Zamboanga City'),
('Christopher John Zobel', 'christopherjohn.zobel@gmail.com', 'Zamboanga City'),
('Matthew Luke Aglipay', 'matthewluke.aglipay@yahoo.com', 'Zamboanga City'),
('Patrick Joseph Bonifacio', 'patrickjoseph.bonifacio@gmail.com', 'Zamboanga City'),
('Ryan Daniel Cojuangco', 'ryandaniel.cojuangco@outlook.com', 'Zamboanga City'),
('Kevin Charles Diokno', 'kevincharles.diokno@gmail.com', 'Zamboanga City'),
('Brian Andrew Escudero', 'brianandrew.escudero@yahoo.com', 'Zamboanga City'),
('Justin Kyle Feliciano', 'justinkyle.feliciano@gmail.com', 'Zamboanga City'),
('Jeremy Scott Gorospe', 'jeremyscott.gorospe@outlook.com', 'Zamboanga City'),
('Tyler James Herrera', 'tylerjames.herrera@gmail.com', 'Zamboanga City'),
('Brandon Lee Inting', 'brandonlee.inting@yahoo.com', 'Zamboanga City'),
('Ethan Cole Jocson', 'ethancole.jocson@gmail.com', 'Zamboanga City'),
('Nathan Reid Kalaw', 'nathanreid.kalaw@outlook.com', 'Zamboanga City'),
('Dylan Chase Lorenzo', 'dylanchase.lorenzo@gmail.com', 'Zamboanga City'),
('Logan Pierce Macaraig', 'loganpierce.macaraig@yahoo.com', 'Zamboanga City'),
('Mason Blake Nepomuceno', 'masonblake.nepomuceno@gmail.com', 'Zamboanga City'),
('Carter Hayes Olivares', 'carterhayes.olivares@outlook.com', 'Zamboanga City'),
('Hunter Dean Pimentel', 'hunterdean.pimentel@gmail.com', 'Zamboanga City'),
('Jayden Cruz Quintos', 'jaydencruz.quintos@yahoo.com', 'Zamboanga City'),
('Aiden Ross Romualdez', 'aidenross.romualdez@gmail.com', 'Zamboanga City'),
('Caleb Finn Salonga', 'calebfinn.salonga@outlook.com', 'Zamboanga City'),
('Maricel Santos', 'maricel.santos123@gmail.com', 'Zamboanga City'),
('Marites Reyes', 'marites.reyes456@yahoo.com', 'Zamboanga City'),
('Marilou Cruz', 'marilou.cruz789@gmail.com', 'Zamboanga City'),
('Maribel Mendoza', 'maribel.mendoza012@outlook.com', 'Zamboanga City'),
('Marilyn Garcia', 'marilyn.garcia345@gmail.com', 'Zamboanga City'),
('Marian Fernandez', 'marian.fernandez678@yahoo.com', 'Zamboanga City'),
('Marissa Torres', 'marissa.torres901@gmail.com', 'Zamboanga City'),
('Marjorie Ramos', 'marjorie.ramos234@outlook.com', 'Zamboanga City'),
('Marlene Dela Cruz', 'marlene.delacruz567@gmail.com', 'Zamboanga City'),
('Margarita Villanueva', 'margarita.villanueva890@yahoo.com', 'Zamboanga City'),
('Melinda Aquino', 'melinda.aquino111@gmail.com', 'Zamboanga City'),
('Melissa Tan', 'melissa.tan222@outlook.com', 'Zamboanga City'),
('Michelle Lopez', 'michelle.lopez333@gmail.com', 'Zamboanga City'),
('Mildred Lim', 'mildred.lim444@yahoo.com', 'Zamboanga City'),
('Minerva Ong', 'minerva.ong555@gmail.com', 'Zamboanga City'),
('Miriam Sy', 'miriam.sy666@outlook.com', 'Zamboanga City'),
('Myra Chua', 'myra.chua777@gmail.com', 'Zamboanga City'),
('Myrna Ang', 'myrna.ang888@yahoo.com', 'Zamboanga City'),
('Nancy Co', 'nancy.co999@gmail.com', 'Zamboanga City'),
('Nelia Dy', 'nelia.dy000@outlook.com', 'Zamboanga City'),
('Nelly Yap', 'nelly.yap101@gmail.com', 'Zamboanga City'),
('Nena Tam', 'nena.tam202@yahoo.com', 'Zamboanga City'),
('Nenita Chung', 'nenita.chung303@gmail.com', 'Zamboanga City'),
('Nida Lee', 'nida.lee404@outlook.com', 'Zamboanga City'),
('Nimfa Wu', 'nimfa.wu505@gmail.com', 'Zamboanga City'),
('Nora Chan', 'nora.chan606@yahoo.com', 'Zamboanga City'),
('Norma Tiu', 'norma.tiu707@gmail.com', 'Zamboanga City'),
('Ofelia Uy', 'ofelia.uy808@outlook.com', 'Zamboanga City'),
('Olivia Yu', 'olivia.yu909@gmail.com', 'Zamboanga City'),
('Pacita Ngo', 'pacita.ngo010@yahoo.com', 'Zamboanga City'),
('Adelaida Bautista', 'adelaida.bautista@gmail.com', 'Zamboanga City'),
('Adelina Pascual', 'adelina.pascual@yahoo.com', 'Zamboanga City'),
('Adela Santiago', 'adela.santiago@gmail.com', 'Zamboanga City'),
('Agripina Rivera', 'agripina.rivera@outlook.com', 'Zamboanga City'),
('Agueda Castro', 'agueda.castro@gmail.com', 'Zamboanga City'),
('Aida Dimaculangan', 'aida.dimaculangan@yahoo.com', 'Zamboanga City'),
('Alberta Manalo', 'alberta.manalo@gmail.com', 'Zamboanga City'),
('Alicia Soriano', 'alicia.soriano@outlook.com', 'Zamboanga City'),
('Alma Mercado', 'alma.mercado@gmail.com', 'Zamboanga City'),
('Amalia Navarro', 'amalia.navarro@yahoo.com', 'Zamboanga City'),
('Amelia Jimenez', 'amelia.jimenez@gmail.com', 'Zamboanga City'),
('Amparo Peralta', 'amparo.peralta@outlook.com', 'Zamboanga City'),
('Ana Medina', 'ana.medina@gmail.com', 'Zamboanga City'),
('Anastacia Aguilar', 'anastacia.aguilar@yahoo.com', 'Zamboanga City'),
('Andrea Flores', 'andrea.flores@gmail.com', 'Zamboanga City'),
('Angela Domingo', 'angela.domingo@outlook.com', 'Zamboanga City'),
('Angelica Salazar', 'angelica.salazar@gmail.com', 'Zamboanga City'),
('Angelina Luna', 'angelina.luna@yahoo.com', 'Zamboanga City'),
('Angelita Espinosa', 'angelita.espinosa@gmail.com', 'Zamboanga City'),
('Anita Magno', 'anita.magno@outlook.com', 'Zamboanga City'),
('Arturo Hernandez', 'arturo.hernandez@gmail.com', 'Zamboanga City'),
('Aurelio Valdez', 'aurelio.valdez@yahoo.com', 'Zamboanga City'),
('Basilio Ocampo', 'basilio.ocampo@gmail.com', 'Zamboanga City'),
('Benedicto Robles', 'benedicto.robles@outlook.com', 'Zamboanga City'),
('Bernardo Castillo', 'bernardo.castillo@gmail.com', 'Zamboanga City'),
('Bonifacio Morales', 'bonifacio.morales@yahoo.com', 'Zamboanga City'),
('Buenaventura Ignacio', 'buenaventura.ignacio@gmail.com', 'Zamboanga City'),
('Calixto Tolentino', 'calixto.tolentino@outlook.com', 'Zamboanga City'),
('Candido Sebastian', 'candido.sebastian@gmail.com', 'Zamboanga City'),
('Carlos Velasco', 'carlos.velasco@yahoo.com', 'Zamboanga City'),
('Celestino Marquez', 'celestino.marquez@gmail.com', 'Zamboanga City'),
('Cipriano Salvador', 'cipriano.salvador@outlook.com', 'Zamboanga City'),
('Claudio Padilla', 'claudio.padilla@gmail.com', 'Zamboanga City'),
('Clemente Miranda', 'clemente.miranda@yahoo.com', 'Zamboanga City'),
('Cornelio Gutierrez', 'cornelio.gutierrez@gmail.com', 'Zamboanga City'),
('Crisostomo Magsaysay', 'crisostomo.magsaysay@outlook.com', 'Zamboanga City'),
('Cristobal Franco', 'cristobal.franco@gmail.com', 'Zamboanga City'),
('Damaso Sarmiento', 'damaso.sarmiento@yahoo.com', 'Zamboanga City'),
('Delfin Perez', 'delfin.perez@gmail.com', 'Zamboanga City'),
('Dionisio Rosales', 'dionisio.rosales@outlook.com', 'Zamboanga City'),
('Domingo Abella', 'domingo.abella@gmail.com', 'Zamboanga City'),
('Eleuterio Buenaventura', 'eleuterio.buenaventura@yahoo.com', 'Zamboanga City'),
('Emiliano Concepcion', 'emiliano.concepcion@gmail.com', 'Zamboanga City'),
('Enrique Delgado', 'enrique.delgado@outlook.com', 'Zamboanga City'),
('Esteban Enriquez', 'esteban.enriquez@gmail.com', 'Zamboanga City'),
('Eugenio Fajardo', 'eugenio.fajardo@yahoo.com', 'Zamboanga City'),
('Eulalio Galang', 'eulalio.galang@gmail.com', 'Zamboanga City'),
('Eusebio Hidalgo', 'eusebio.hidalgo@outlook.com', 'Zamboanga City'),
('Fermin Imperial', 'fermin.imperial@gmail.com', 'Zamboanga City'),
('Fidel Jacinto', 'fidel.jacinto@yahoo.com', 'Zamboanga City'),
('Florencio Kapunan', 'florencio.kapunan@gmail.com', 'Zamboanga City'),
('Florentino Lacson', 'florentino.lacson@outlook.com', 'Zamboanga City'),
('Francisco Macapagal', 'francisco.macapagal@gmail.com', 'Zamboanga City'),
('Gabriel Nakpil', 'gabriel.nakpil@yahoo.com', 'Zamboanga City'),
('Gaudencio Ongpin', 'gaudencio.ongpin@gmail.com', 'Zamboanga City'),
('Gerardo Palma', 'gerardo.palma@outlook.com', 'Zamboanga City'),
('Gilberto Quijano', 'gilberto.quijano@gmail.com', 'Zamboanga City'),
('Godofredo Razon', 'godofredo.razon@yahoo.com', 'Zamboanga City'),
('Gonzalo Sotto', 'gonzalo.sotto@gmail.com', 'Zamboanga City'),
('Graciano Tanco', 'graciano.tanco@outlook.com', 'Zamboanga City'),
('Gregorio Ubaldo', 'gregorio.ubaldo@gmail.com', 'Zamboanga City'),
('Guillermo Vargas', 'guillermo.vargas@yahoo.com', 'Zamboanga City'),
('Heraclio Yulo', 'heraclio.yulo@gmail.com', 'Zamboanga City'),
('Herminio Zamora', 'herminio.zamora@outlook.com', 'Zamboanga City'),
('Honorio Abaya', 'honorio.abaya@gmail.com', 'Zamboanga City'),
('Ignacio Bacani', 'ignacio.bacani@yahoo.com', 'Zamboanga City'),
('Inocencio Cabrera', 'inocencio.cabrera@gmail.com', 'Zamboanga City'),
('Isabelo Dalisay', 'isabelo.dalisay@outlook.com', 'Zamboanga City'),
('Isidoro Escoda', 'isidoro.escoda@gmail.com', 'Zamboanga City'),
('Jennylyn Fontanilla', 'jennylyn.fontanilla@yahoo.com', 'Zamboanga City'),
('Jessa Gonzaga', 'jessa.gonzaga@gmail.com', 'Zamboanga City'),
('Jessie Halili', 'jessie.halili@outlook.com', 'Zamboanga City'),
('Joanna Ilagan', 'joanna.ilagan@gmail.com', 'Zamboanga City'),
('Jocelyn Javier', 'jocelyn.javier@yahoo.com', 'Zamboanga City'),
('Jonalyn Katigbak', 'jonalyn.katigbak@gmail.com', 'Zamboanga City'),
('Josefina Laurel', 'josefina.laurel@outlook.com', 'Zamboanga City'),
('Josephine Madrigal', 'josephine.madrigal@gmail.com', 'Zamboanga City'),
('Jovelyn Natividad', 'jovelyn.natividad@yahoo.com', 'Zamboanga City'),
('Joyce Osmena', 'joyce.osmena@gmail.com', 'Zamboanga City'),
('Julieta Pangilinan', 'julieta.pangilinan@outlook.com', 'Zamboanga City'),
('Katrina Quezon', 'katrina.quezon@gmail.com', 'Zamboanga City'),
('Kaye Recto', 'kaye.recto@yahoo.com', 'Zamboanga City'),
('Khristine Sison', 'khristine.sison@gmail.com', 'Zamboanga City'),
('Kimberly Tantoco', 'kimberly.tantoco@outlook.com', 'Zamboanga City'),
('Lea Urquiola', 'lea.urquiola@gmail.com', 'Zamboanga City'),
('Leah Villamor', 'leah.villamor@yahoo.com', 'Zamboanga City'),
('Leilani Wenceslao', 'leilani.wenceslao@gmail.com', 'Zamboanga City'),
('Leonora Yabut', 'leonora.yabut@outlook.com', 'Zamboanga City'),
('Leticia Zobel', 'leticia.zobel@gmail.com', 'Zamboanga City'),
('Ligaya Aglipay', 'ligaya.aglipay@yahoo.com', 'Zamboanga City'),
('Lilia Bonifacio', 'lilia.bonifacio@gmail.com', 'Zamboanga City'),
('Lina Cojuangco', 'lina.cojuangco@outlook.com', 'Zamboanga City'),
('Linda Diokno', 'linda.diokno@gmail.com', 'Zamboanga City'),
('Lorna Escudero', 'lorna.escudero@yahoo.com', 'Zamboanga City'),
('Lucena Feliciano', 'lucena.feliciano@gmail.com', 'Zamboanga City'),
('Lucila Gorospe', 'lucila.gorospe@outlook.com', 'Zamboanga City'),
('Luisa Herrera', 'luisa.herrera@gmail.com', 'Zamboanga City'),
('Luzviminda Inting', 'luzviminda.inting@yahoo.com', 'Zamboanga City'),
('Lydia Jocson', 'lydia.jocson@gmail.com', 'Zamboanga City'),

-- Filipino Names - Other Philippine Cities (45 records: 456-500)
('Mabuhay Kalaw', 'mabuhay.kalaw@gmail.com', 'Cebu City'),
('Makisig Lorenzo', 'makisig.lorenzo@outlook.com', 'Davao City'),
('Malaya Macaraig', 'malaya.macaraig@yahoo.com', 'Manila'),
('Maliksi Nepomuceno', 'maliksi.nepomuceno@gmail.com', 'Quezon City'),
('Mapagmahal Olivares', 'mapagmahal.olivares@outlook.com', 'Makati'),
('Marilag Pimentel', 'marilag.pimentel@gmail.com', 'Pasig'),
('Masaya Quintos', 'masaya.quintos@yahoo.com', 'Taguig'),
('Masigla Romualdez', 'masigla.romualdez@gmail.com', 'Iloilo City'),
('Matapang Salonga', 'matapang.salonga@outlook.com', 'Bacolod'),
('Mayumi Trinidad', 'mayumi.trinidad@gmail.com', 'Cagayan de Oro'),
('Hiraya Ungson', 'hiraya.ungson@yahoo.com', 'General Santos'),
('Lakambini Valera', 'lakambini.valera@gmail.com', 'Baguio'),
('Bituin Wenceslao', 'bituin.wenceslao@outlook.com', 'Cebu City'),
('Haliya Ysip', 'haliya.ysip@gmail.com', 'Davao City'),
('Mayari Zarate', 'mayari.zarate@yahoo.com', 'Angeles City'),
('Tala Abad', 'tala.abad@gmail.com', 'San Fernando'),
('Diwa Bello', 'diwa.bello@outlook.com', 'Lipa'),
('Bathala Cariño', 'bathala.carino@gmail.com', 'Batangas City'),
('Sinag Dacquel', 'sinag.dacquel@yahoo.com', 'Lucena'),
('Araw Evidente', 'araw.evidente@gmail.com', 'Tagaytay'),
('Diwata Faustino', 'diwata.faustino@outlook.com', 'Dagupan'),
('Engkanto Gatchalian', 'engkanto.gatchalian@gmail.com', 'Vigan'),
('Tikbalang Hontiveros', 'tikbalang.hontiveros@yahoo.com', 'Antipolo'),
('Duende Inchausti', 'duende.inchausti@gmail.com', 'Caloocan'),
('Kapre Jalandoni', 'kapre.jalandoni@outlook.com', 'Parañaque'),
('Reynaldo Angeles', 'reynaldo.angeles@gmail.com', 'Las Piñas'),
('Rosalinda Bulacan', 'rosalinda.bulacan@yahoo.com', 'Mandaluyong'),
('Ruben Cavite', 'ruben.cavite@gmail.com', 'San Juan'),
('Rufino Dagupan', 'rufino.dagupan@outlook.com', 'Marikina'),
('Ruth Ester', 'ruth.ester@gmail.com', 'Valenzuela'),
('Salvador Florentino', 'salvador.florentino@yahoo.com', 'Cebu City'),
('Samuel Guerrero', 'samuel.guerrero@gmail.com', 'Davao City'),
('Sancho Hortaleza', 'sancho.hortaleza@outlook.com', 'Manila'),
('Santiago Ilustrado', 'santiago.ilustrado@gmail.com', 'Quezon City'),
('Saturnino Jollibee', 'saturnino.jollibee@yahoo.com', 'Makati'),
('Sebastian Kalayaan', 'sebastian.kalayaan@gmail.com', 'Pasig'),
('Sergio Libertad', 'sergio.libertad@outlook.com', 'Taguig'),
('Silvestre Magdalo', 'silvestre.magdalo@gmail.com', 'Iloilo City'),
('Simeon Nagcarlan', 'simeon.nagcarlan@yahoo.com', 'Bacolod'),
('Socorro Olongapo', 'socorro.olongapo@gmail.com', 'Cagayan de Oro'),
('Soledad Pangasinan', 'soledad.pangasinan@outlook.com', 'General Santos'),
('Teresita Quezon', 'teresita.quezon@gmail.com', 'Baguio'),
('Vicente Roxas', 'vicente.roxas@yahoo.com', 'Cebu City'),
('Victoria Subic', 'victoria.subic@gmail.com', 'Davao City'),
('Zenaida Tarlac', 'zenaida.tarlac@outlook.com', 'Manila'),
('Wilfredo Umali', 'wilfredo.umali@gmail.com', 'Quezon City'),
('Xyza Vizcaya', 'xyza.vizcaya@yahoo.com', 'Makati'),

-- Additional Pet-like/Nickname Names - Zamboanga City (501-600)
('Snickers Abalos', 'snickers.abalos@gmail.com', 'Zamboanga City'),
('Twix Baluyot', 'twix.baluyot@yahoo.com', 'Zamboanga City'),
('KitKat Caguioa', 'kitkat.caguioa@gmail.com', 'Zamboanga City'),
('Reeses Dagohoy', 'reeses.dagohoy@outlook.com', 'Zamboanga City'),
('Skittles Elizalde', 'skittles.elizalde@gmail.com', 'Zamboanga City'),
('MnMs Fuentebella', 'mnms.fuentebella@yahoo.com', 'Zamboanga City'),
('Hershey Golez', 'hershey.golez@gmail.com', 'Zamboanga City'),
('Milky Halili', 'milky.halili@outlook.com', 'Zamboanga City'),
('Cadbury Ignacio', 'cadbury.ignacio@gmail.com', 'Zamboanga City'),
('Toblerone Javellana', 'toblerone.javellana@yahoo.com', 'Zamboanga City'),
('Ferrero Kapalong', 'ferrero.kapalong@gmail.com', 'Zamboanga City'),
('Lindt Lacsamana', 'lindt.lacsamana@outlook.com', 'Zamboanga City'),
('Godiva Malvar', 'godiva.malvar@gmail.com', 'Zamboanga City'),
('Ghirardelli Nantes', 'ghirardelli.nantes@yahoo.com', 'Zamboanga City'),
('Nutella Oblea', 'nutella.oblea@gmail.com', 'Zamboanga City'),
('Pocky Panganiban', 'pocky.panganiban@outlook.com', 'Zamboanga City'),
('Pepero Quiambao', 'pepero.quiambao@gmail.com', 'Zamboanga City'),
('Choco Realubit', 'choco.realubit@yahoo.com', 'Zamboanga City'),
('Fudge Salcedo', 'fudge.salcedo@gmail.com', 'Zamboanga City'),
('Truffle Tabunda', 'truffle.tabunda@outlook.com', 'Zamboanga City'),
('Bonbon Uson', 'bonbon.uson@gmail.com', 'Zamboanga City'),
('Praline Velarde', 'praline.velarde@yahoo.com', 'Zamboanga City'),
('Ganache Wangco', 'ganache.wangco@gmail.com', 'Zamboanga City'),
('Mousse Xyza', 'mousse.xyza@outlook.com', 'Zamboanga City'),
('Souffle Yaptinchay', 'souffle.yaptinchay@gmail.com', 'Zamboanga City'),
('Parfait Zafra', 'parfait.zafra@yahoo.com', 'Zamboanga City'),
('Gelato Abundo', 'gelato.abundo@gmail.com', 'Zamboanga City'),
('Sorbet Buencamino', 'sorbet.buencamino@outlook.com', 'Zamboanga City'),
('Sherbet Calipusan', 'sherbet.calipusan@gmail.com', 'Zamboanga City'),
('Sundae Dimzon', 'sundae.dimzon@yahoo.com', 'Zamboanga City'),
('Popsicle Embate', 'popsicle.embate@gmail.com', 'Zamboanga City'),
('Frosty Fullido', 'frosty.fullido@outlook.com', 'Zamboanga City'),
('Slushie Gabutan', 'slushie.gabutan@gmail.com', 'Zamboanga City'),
('Smoothie Habalo', 'smoothie.habalo@yahoo.com', 'Zamboanga City'),
('Milkshake Ibanez', 'milkshake.ibanez@gmail.com', 'Zamboanga City'),
('Frappe Jamilla', 'frappe.jamilla@outlook.com', 'Zamboanga City'),
('Lemonade Kintanar', 'lemonade.kintanar@gmail.com', 'Zamboanga City'),
('Citrus Laguda', 'citrus.laguda@yahoo.com', 'Zamboanga City'),
('Melon Mabasa', 'melon.mabasa@gmail.com', 'Zamboanga City'),
('Grape Nograles', 'grape.nograles@outlook.com', 'Zamboanga City'),
('Orange Ochotorena', 'orange.ochotorena@gmail.com', 'Zamboanga City'),
('Lemon Palang', 'lemon.palang@yahoo.com', 'Zamboanga City'),
('Lime Quevedo', 'lime.quevedo@gmail.com', 'Zamboanga City'),
('Tangerine Rabang', 'tangerine.rabang@outlook.com', 'Zamboanga City'),
('Clementine Sabado', 'clementine.sabado@gmail.com', 'Zamboanga City'),
('Kumquat Tabayoyong', 'kumquat.tabayoyong@yahoo.com', 'Zamboanga City'),
('Pomelo Ubay', 'pomelo.ubay@gmail.com', 'Zamboanga City'),
('Guava Valdoria', 'guava.valdoria@outlook.com', 'Zamboanga City'),
('Starfruit Wong', 'starfruit.wong@gmail.com', 'Zamboanga City'),
('Dragonfruit Yoingco', 'dragonfruit.yoingco@yahoo.com', 'Zamboanga City'),
('Lychee Zepeda', 'lychee.zepeda@gmail.com', 'Zamboanga City'),
('Rambutan Alcantara', 'rambutan.alcantara@outlook.com', 'Zamboanga City'),
('Durian Balagtas', 'durian.balagtas@gmail.com', 'Zamboanga City'),
('Jackfruit Casimiro', 'jackfruit.casimiro@yahoo.com', 'Zamboanga City'),
('Mangosteen Dagdag', 'mangosteen.dagdag@gmail.com', 'Zamboanga City'),
('Chestnut Esteban', 'chestnut.esteban@outlook.com', 'Zamboanga City'),
('Hazelnut Fortaleza', 'hazelnut.fortaleza@gmail.com', 'Zamboanga City'),
('Pistachio Goyena', 'pistachio.goyena@yahoo.com', 'Zamboanga City'),
('Cashew Hermosura', 'cashew.hermosura@gmail.com', 'Zamboanga City'),
('Almond Ibardolaza', 'almond.ibardolaza@outlook.com', 'Zamboanga City'),
('Walnut Joquino', 'walnut.joquino@gmail.com', 'Zamboanga City'),
('Pecan Kabigting', 'pecan.kabigting@yahoo.com', 'Zamboanga City'),
('Macadamia Lacanilao', 'macadamia.lacanilao@gmail.com', 'Zamboanga City'),
('Peanut Malaluan', 'peanut.malaluan@outlook.com', 'Zamboanga City'),
('Acorn Naguit', 'acorn.naguit@gmail.com', 'Zamboanga City'),
('Hickory Olarte', 'hickory.olarte@yahoo.com', 'Zamboanga City'),
('Cedar Parado', 'cedar.parado@gmail.com', 'Zamboanga City'),
('Willow Quintero', 'willow.quintero@outlook.com', 'Zamboanga City'),
('Maple Ramirez', 'maple.ramirez@gmail.com', 'Zamboanga City'),
('Oak Samonte', 'oak.samonte@yahoo.com', 'Zamboanga City'),
('Pine Tabile', 'pine.tabile@gmail.com', 'Zamboanga City'),
('Birch Umipig', 'birch.umipig@outlook.com', 'Zamboanga City'),
('Ash Villaruel', 'ash.villaruel@gmail.com', 'Zamboanga City'),
('Elm Walung', 'elm.walung@yahoo.com', 'Zamboanga City'),
('Spruce Yadao', 'spruce.yadao@gmail.com', 'Zamboanga City'),
('Juniper Zapanta', 'juniper.zapanta@outlook.com', 'Zamboanga City'),
('Cypress Alegre', 'cypress.alegre@gmail.com', 'Zamboanga City'),
('Sequoia Banaag', 'sequoia.banaag@yahoo.com', 'Zamboanga City'),
('Redwood Catalan', 'redwood.catalan@gmail.com', 'Zamboanga City'),
('Magnolia Dayao', 'magnolia.dayao@outlook.com', 'Zamboanga City'),
('Sakura Encabo', 'sakura.encabo@gmail.com', 'Zamboanga City'),
('Blossom Flores', 'blossom.flores@yahoo.com', 'Zamboanga City'),
('Petal Guevara', 'petal.guevara@gmail.com', 'Zamboanga City'),
('Bloom Hechanova', 'bloom.hechanova@outlook.com', 'Zamboanga City'),
('Bud Ildefonso', 'bud.ildefonso@gmail.com', 'Zamboanga City'),
('Leaf Jongco', 'leaf.jongco@yahoo.com', 'Zamboanga City'),
('Stem Kho', 'stem.kho@gmail.com', 'Zamboanga City'),
('Thorn Lacuata', 'thorn.lacuata@outlook.com', 'Zamboanga City'),
('Moss Macalalad', 'moss.macalalad@gmail.com', 'Zamboanga City'),
('Lichen Naldo', 'lichen.naldo@yahoo.com', 'Zamboanga City'),
('Fern Oledan', 'fern.oledan@gmail.com', 'Zamboanga City'),
('Ivy Pagaduan', 'ivy.pagaduan@outlook.com', 'Zamboanga City'),
('Vine Quiogue', 'vine.quiogue@gmail.com', 'Zamboanga City'),
('Reed Rondilla', 'reed.rondilla@yahoo.com', 'Zamboanga City'),
('Bamboo Sarte', 'bamboo.sarte@gmail.com', 'Zamboanga City'),
('Lotus Tanco', 'lotus.tanco@outlook.com', 'Zamboanga City'),
('Lily Urbiztondo', 'lily.urbiztondo@gmail.com', 'Zamboanga City'),

-- Additional Pet-like/Nickname Names - Other PH Cities (601-640)
('Puddles Albano', 'puddles.albano@gmail.com', 'Cebu City'),
('Ripple Banaag', 'ripple.banaag@yahoo.com', 'Davao City'),
('Splash Cariaga', 'splash.cariaga@gmail.com', 'Manila'),
('Bubble Dela Rama', 'bubble.delarama@outlook.com', 'Quezon City'),
('Droplet Evangelista', 'droplet.evangelista@gmail.com', 'Makati'),
('Misty Fabregas', 'misty.fabregas@yahoo.com', 'Pasig'),
('Dewey Guillermo', 'dewey.guillermo@gmail.com', 'Taguig'),
('Foggy Henson', 'foggy.henson@outlook.com', 'Iloilo City'),
('Cloudy Imperial', 'cloudy.imperial@gmail.com', 'Bacolod'),
('Stormy Jaramillo', 'stormy.jaramillo@yahoo.com', 'Cagayan de Oro'),
('Thunder Kaluag', 'thunder.kaluag@gmail.com', 'General Santos'),
('Lightning Layug', 'lightning.layug@outlook.com', 'Baguio'),
('Bolt Madarang', 'bolt.madarang@gmail.com', 'Cebu City'),
('Flash Nolasco', 'flash.nolasco@yahoo.com', 'Davao City'),
('Blitz Opulencia', 'blitz.opulencia@gmail.com', 'Angeles City'),
('Dash Pagsibigan', 'dash.pagsibigan@outlook.com', 'San Fernando'),
('Zoom Quimpo', 'zoom.quimpo@gmail.com', 'Lipa'),
('Swift Roque', 'swift.roque@yahoo.com', 'Batangas City'),
('Rocket Salatan', 'rocket.salatan@gmail.com', 'Lucena'),
('Comet Talion', 'comet.talion@outlook.com', 'Tagaytay'),
('Star Umali', 'star.umali@gmail.com', 'Dagupan'),
('Nova Villaflor', 'nova.villaflor@yahoo.com', 'Vigan'),
('Galaxy Winson', 'galaxy.winson@gmail.com', 'Antipolo'),
('Nebula Yuseco', 'nebula.yuseco@outlook.com', 'Caloocan'),
('Cosmos Zaragoza', 'cosmos.zaragoza@gmail.com', 'Parañaque'),
('Aurora Ang', 'aurora.ang@yahoo.com', 'Las Piñas'),
('Eclipse Beltran', 'eclipse.beltran@gmail.com', 'Mandaluyong'),
('Solstice Capulong', 'solstice.capulong@outlook.com', 'San Juan'),
('Equinox Dionisio', 'equinox.dionisio@gmail.com', 'Marikina'),
('Zenith Edralin', 'zenith.edralin@yahoo.com', 'Valenzuela'),
('Apex Fermin', 'apex.fermin@gmail.com', 'Cebu City'),
('Summit Gochangco', 'summit.gochangco@outlook.com', 'Davao City'),
('Peak Hilario', 'peak.hilario@gmail.com', 'Manila'),
('Crest Inocentes', 'crest.inocentes@yahoo.com', 'Quezon City'),
('Ridge Javelosa', 'ridge.javelosa@gmail.com', 'Makati'),
('Valley Kabiling', 'valley.kabiling@outlook.com', 'Pasig'),
('Canyon Lacaba', 'canyon.lacaba@gmail.com', 'Taguig'),
('Cliff Macasaet', 'cliff.macasaet@yahoo.com', 'Iloilo City'),
('Boulder Navarrete', 'boulder.navarrete@gmail.com', 'Bacolod'),
('Pebble Oclarit', 'pebble.oclarit@outlook.com', 'Cagayan de Oro'),

-- Additional Filipino Names - Zamboanga City (641-900)
('Abelardo Santos', 'abelardo.santos@gmail.com', 'Zamboanga City'),
('Abundio Reyes', 'abundio.reyes@yahoo.com', 'Zamboanga City'),
('Acacio Cruz', 'acacio.cruz@gmail.com', 'Zamboanga City'),
('Adalberto Mendoza', 'adalberto.mendoza@outlook.com', 'Zamboanga City'),
('Adelfo Garcia', 'adelfo.garcia@gmail.com', 'Zamboanga City'),
('Adolfo Fernandez', 'adolfo.fernandez@yahoo.com', 'Zamboanga City'),
('Adoracion Torres', 'adoracion.torres@gmail.com', 'Zamboanga City'),
('Adriano Ramos', 'adriano.ramos@outlook.com', 'Zamboanga City'),
('Agapito Dela Cruz', 'agapito.delacruz@gmail.com', 'Zamboanga City'),
('Agatona Villanueva', 'agatona.villanueva@yahoo.com', 'Zamboanga City'),
('Aglaia Aquino', 'aglaia.aquino@gmail.com', 'Zamboanga City'),
('Agustin Tan', 'agustin.tan@outlook.com', 'Zamboanga City'),
('Alaida Lopez', 'alaida.lopez@gmail.com', 'Zamboanga City'),
('Alarico Lim', 'alarico.lim@yahoo.com', 'Zamboanga City'),
('Albino Ong', 'albino.ong@gmail.com', 'Zamboanga City'),
('Alcides Sy', 'alcides.sy@outlook.com', 'Zamboanga City'),
('Alegria Chua', 'alegria.chua@gmail.com', 'Zamboanga City'),
('Alejo Ang', 'alejo.ang@yahoo.com', 'Zamboanga City'),
('Alfonso Co', 'alfonso.co@gmail.com', 'Zamboanga City'),
('Alfonsina Dy', 'alfonsina.dy@outlook.com', 'Zamboanga City'),
('Alipio Yap', 'alipio.yap@gmail.com', 'Zamboanga City'),
('Altagracia Tam', 'altagracia.tam@yahoo.com', 'Zamboanga City'),
('Amado Chung', 'amado.chung@gmail.com', 'Zamboanga City'),
('Amador Lee', 'amador.lee@outlook.com', 'Zamboanga City'),
('Amalio Wu', 'amalio.wu@gmail.com', 'Zamboanga City'),
('Amancio Chan', 'amancio.chan@yahoo.com', 'Zamboanga City'),
('Amanda Tiu', 'amanda.tiu@gmail.com', 'Zamboanga City'),
('Ambrosia Uy', 'ambrosia.uy@outlook.com', 'Zamboanga City'),
('Amedeo Yu', 'amedeo.yu@gmail.com', 'Zamboanga City'),
('Amelita Ngo', 'amelita.ngo@yahoo.com', 'Zamboanga City'),
('Anacleto Bautista', 'anacleto.bautista@gmail.com', 'Zamboanga City'),
('Anatolio Pascual', 'anatolio.pascual@outlook.com', 'Zamboanga City'),
('Andres Santiago', 'andres.santiago@gmail.com', 'Zamboanga City'),
('Aniceto Rivera', 'aniceto.rivera@yahoo.com', 'Zamboanga City'),
('Anselmo Castro', 'anselmo.castro@gmail.com', 'Zamboanga City'),
('Antonina Dimaculangan', 'antonina.dimaculangan@outlook.com', 'Zamboanga City'),
('Antonieta Manalo', 'antonieta.manalo@gmail.com', 'Zamboanga City'),
('Aparicio Soriano', 'aparicio.soriano@yahoo.com', 'Zamboanga City'),
('Apolinar Mercado', 'apolinar.mercado@gmail.com', 'Zamboanga City'),
('Aquilina Navarro', 'aquilina.navarro@outlook.com', 'Zamboanga City'),
('Arcadio Jimenez', 'arcadio.jimenez@gmail.com', 'Zamboanga City'),
('Arcangel Peralta', 'arcangel.peralta@yahoo.com', 'Zamboanga City'),
('Arecio Medina', 'arecio.medina@gmail.com', 'Zamboanga City'),
('Argimiro Aguilar', 'argimiro.aguilar@outlook.com', 'Zamboanga City'),
('Aristeo Flores', 'aristeo.flores@gmail.com', 'Zamboanga City'),
('Arminda Domingo', 'arminda.domingo@yahoo.com', 'Zamboanga City'),
('Arnaldo Salazar', 'arnaldo.salazar@gmail.com', 'Zamboanga City'),
('Arnulfo Luna', 'arnulfo.luna@outlook.com', 'Zamboanga City'),
('Arsenio Espinosa', 'arsenio.espinosa@gmail.com', 'Zamboanga City'),
('Artemio Magno', 'artemio.magno@yahoo.com', 'Zamboanga City'),
('Asisclo Hernandez', 'asisclo.hernandez@gmail.com', 'Zamboanga City'),
('Atanasio Valdez', 'atanasio.valdez@outlook.com', 'Zamboanga City'),
('Atilano Ocampo', 'atilano.ocampo@gmail.com', 'Zamboanga City'),
('Augusto Robles', 'augusto.robles@yahoo.com', 'Zamboanga City'),
('Aurelia Castillo', 'aurelia.castillo@gmail.com', 'Zamboanga City'),
('Aureliano Morales', 'aureliano.morales@outlook.com', 'Zamboanga City'),
('Aurora Ignacio', 'aurora.ignacio@gmail.com', 'Zamboanga City'),
('Avelina Tolentino', 'avelina.tolentino@yahoo.com', 'Zamboanga City'),
('Avelino Sebastian', 'avelino.sebastian@gmail.com', 'Zamboanga City'),
('Balbina Velasco', 'balbina.velasco@outlook.com', 'Zamboanga City'),
('Balbino Marquez', 'balbino.marquez@gmail.com', 'Zamboanga City'),
('Baldomero Salvador', 'baldomero.salvador@yahoo.com', 'Zamboanga City'),
('Bartolome Padilla', 'bartolome.padilla@gmail.com', 'Zamboanga City'),
('Basilisa Miranda', 'basilisa.miranda@outlook.com', 'Zamboanga City'),
('Basilides Gutierrez', 'basilides.gutierrez@gmail.com', 'Zamboanga City'),
('Beatriz Magsaysay', 'beatriz.magsaysay@yahoo.com', 'Zamboanga City'),
('Belen Franco', 'belen.franco@gmail.com', 'Zamboanga City'),
('Belinda Sarmiento', 'belinda.sarmiento@outlook.com', 'Zamboanga City'),
('Belisario Perez', 'belisario.perez@gmail.com', 'Zamboanga City'),
('Benilda Rosales', 'benilda.rosales@yahoo.com', 'Zamboanga City'),
('Benigna Abella', 'benigna.abella@gmail.com', 'Zamboanga City'),
('Benito Buenaventura', 'benito.buenaventura@outlook.com', 'Zamboanga City'),
('Benjamin Concepcion', 'benjamin.concepcion@gmail.com', 'Zamboanga City'),
('Berenice Delgado', 'berenice.delgado@yahoo.com', 'Zamboanga City'),
('Bernardina Enriquez', 'bernardina.enriquez@gmail.com', 'Zamboanga City'),
('Bibiana Fajardo', 'bibiana.fajardo@outlook.com', 'Zamboanga City'),
('Bienvenido Galang', 'bienvenido.galang@gmail.com', 'Zamboanga City'),
('Blandina Hidalgo', 'blandina.hidalgo@yahoo.com', 'Zamboanga City'),
('Bonifacia Imperial', 'bonifacia.imperial@gmail.com', 'Zamboanga City'),
('Brigida Jacinto', 'brigida.jacinto@outlook.com', 'Zamboanga City'),
('Bruno Kapunan', 'bruno.kapunan@gmail.com', 'Zamboanga City'),
('Buenaventura Lacson', 'buenaventura.lacson@yahoo.com', 'Zamboanga City'),
('Calixtro Macapagal', 'calixtro.macapagal@gmail.com', 'Zamboanga City'),
('Camila Nakpil', 'camila.nakpil@outlook.com', 'Zamboanga City'),
('Camilo Ongpin', 'camilo.ongpin@gmail.com', 'Zamboanga City'),
('Candelaria Palma', 'candelaria.palma@yahoo.com', 'Zamboanga City'),
('Canuto Quijano', 'canuto.quijano@gmail.com', 'Zamboanga City'),
('Caridad Razon', 'caridad.razon@outlook.com', 'Zamboanga City'),
('Carlito Sotto', 'carlito.sotto@gmail.com', 'Zamboanga City'),
('Carolina Tanco', 'carolina.tanco@yahoo.com', 'Zamboanga City'),
('Casiano Ubaldo', 'casiano.ubaldo@gmail.com', 'Zamboanga City'),
('Casilda Vargas', 'casilda.vargas@outlook.com', 'Zamboanga City'),
('Casimiro Yulo', 'casimiro.yulo@gmail.com', 'Zamboanga City'),
('Catalina Zamora', 'catalina.zamora@yahoo.com', 'Zamboanga City'),
('Catarino Abaya', 'catarino.abaya@gmail.com', 'Zamboanga City'),
('Cayetano Bacani', 'cayetano.bacani@outlook.com', 'Zamboanga City'),
('Cecilio Cabrera', 'cecilio.cabrera@gmail.com', 'Zamboanga City'),
('Ceferino Dalisay', 'ceferino.dalisay@yahoo.com', 'Zamboanga City'),
('Celia Escoda', 'celia.escoda@gmail.com', 'Zamboanga City'),
('Celso Fontanilla', 'celso.fontanilla@outlook.com', 'Zamboanga City'),
('Cenon Gonzaga', 'cenon.gonzaga@gmail.com', 'Zamboanga City'),
('Cesareo Halili', 'cesareo.halili@yahoo.com', 'Zamboanga City'),
('Cirilo Ilagan', 'cirilo.ilagan@gmail.com', 'Zamboanga City'),
('Cipriana Javier', 'cipriana.javier@outlook.com', 'Zamboanga City'),
('Ciriaco Katigbak', 'ciriaco.katigbak@gmail.com', 'Zamboanga City'),
('Clarinda Laurel', 'clarinda.laurel@yahoo.com', 'Zamboanga City'),
('Claro Madrigal', 'claro.madrigal@gmail.com', 'Zamboanga City'),
('Claudia Natividad', 'claudia.natividad@outlook.com', 'Zamboanga City'),
('Claudio Osmena', 'claudio.osmena@gmail.com', 'Zamboanga City'),
('Clemencia Pangilinan', 'clemencia.pangilinan@yahoo.com', 'Zamboanga City'),
('Cleofe Quezon', 'cleofe.quezon@gmail.com', 'Zamboanga City'),
('Clotilde Recto', 'clotilde.recto@outlook.com', 'Zamboanga City'),
('Conceso Sison', 'conceso.sison@gmail.com', 'Zamboanga City'),
('Consolacion Tantoco', 'consolacion.tantoco@yahoo.com', 'Zamboanga City'),
('Constancia Urquiola', 'constancia.urquiola@gmail.com', 'Zamboanga City'),
('Consuelo Villamor', 'consuelo.villamor@outlook.com', 'Zamboanga City'),
('Corazon Wenceslao', 'corazon.wenceslao@gmail.com', 'Zamboanga City'),
('Cresencia Yabut', 'cresencia.yabut@yahoo.com', 'Zamboanga City'),
('Crescencio Zobel', 'crescencio.zobel@gmail.com', 'Zamboanga City'),
('Crisanta Aglipay', 'crisanta.aglipay@outlook.com', 'Zamboanga City'),
('Crisostomo Bonifacio', 'crisostomo.bonifacio@gmail.com', 'Zamboanga City'),
('Cristeta Cojuangco', 'cristeta.cojuangco@yahoo.com', 'Zamboanga City'),
('Cristina Diokno', 'cristina.diokno@gmail.com', 'Zamboanga City'),
('Cristino Escudero', 'cristino.escudero@outlook.com', 'Zamboanga City'),
('Dalmacio Feliciano', 'dalmacio.feliciano@gmail.com', 'Zamboanga City'),
('Damiana Gorospe', 'damiana.gorospe@yahoo.com', 'Zamboanga City'),
('Danilo Herrera', 'danilo.herrera@gmail.com', 'Zamboanga City'),
('Daria Inting', 'daria.inting@outlook.com', 'Zamboanga City'),
('Delfina Jocson', 'delfina.jocson@gmail.com', 'Zamboanga City'),
('Demetria Kalaw', 'demetria.kalaw@yahoo.com', 'Zamboanga City'),
('Deogracias Lorenzo', 'deogracias.lorenzo@gmail.com', 'Zamboanga City'),
('Desiderio Macaraig', 'desiderio.macaraig@outlook.com', 'Zamboanga City'),
('Diana Nepomuceno', 'diana.nepomuceno@gmail.com', 'Zamboanga City'),
('Digna Olivares', 'digna.olivares@yahoo.com', 'Zamboanga City'),
('Diocles Pimentel', 'diocles.pimentel@gmail.com', 'Zamboanga City'),
('Dionisia Quintos', 'dionisia.quintos@outlook.com', 'Zamboanga City'),
('Dolores Romualdez', 'dolores.romualdez@gmail.com', 'Zamboanga City'),
('Domiciano Salonga', 'domiciano.salonga@yahoo.com', 'Zamboanga City'),
('Dominador Trinidad', 'dominador.trinidad@gmail.com', 'Zamboanga City'),
('Dominga Ungson', 'dominga.ungson@outlook.com', 'Zamboanga City'),
('Dorotea Valera', 'dorotea.valera@gmail.com', 'Zamboanga City'),
('Doroteo Wenceslao', 'doroteo.wenceslao@yahoo.com', 'Zamboanga City'),
('Edelmira Ysip', 'edelmira.ysip@gmail.com', 'Zamboanga City'),
('Edgardo Zarate', 'edgardo.zarate@outlook.com', 'Zamboanga City'),
('Edmundo Abad', 'edmundo.abad@gmail.com', 'Zamboanga City'),
('Eduardo Bello', 'eduardo.bello@yahoo.com', 'Zamboanga City'),
('Eduvigis Carino', 'eduvigis.carino@gmail.com', 'Zamboanga City'),
('Efigenia Dacquel', 'efigenia.dacquel@outlook.com', 'Zamboanga City'),
('Efigenio Evidente', 'efigenio.evidente@gmail.com', 'Zamboanga City'),
('Efrain Faustino', 'efrain.faustino@yahoo.com', 'Zamboanga City'),
('Eladia Gatchalian', 'eladia.gatchalian@gmail.com', 'Zamboanga City'),
('Eleno Hontiveros', 'eleno.hontiveros@outlook.com', 'Zamboanga City'),
('Eleonor Inchausti', 'eleonor.inchausti@gmail.com', 'Zamboanga City'),
('Elia Jalandoni', 'elia.jalandoni@yahoo.com', 'Zamboanga City'),
('Elias Kasilag', 'elias.kasilag@gmail.com', 'Zamboanga City'),
('Elisa Legarda', 'elisa.legarda@outlook.com', 'Zamboanga City'),
('Elisea Maceda', 'elisea.maceda@gmail.com', 'Zamboanga City'),
('Eliseo Nakpil', 'eliseo.nakpil@yahoo.com', 'Zamboanga City'),
('Elvira Ongpin', 'elvira.ongpin@gmail.com', 'Zamboanga City'),
('Emigdio Palanca', 'emigdio.palanca@outlook.com', 'Zamboanga City'),
('Emilia Quimpo', 'emilia.quimpo@gmail.com', 'Zamboanga City'),
('Emma Reyson', 'emma.reyson@yahoo.com', 'Zamboanga City'),
('Emmanuel Syjuco', 'emmanuel.syjuco@gmail.com', 'Zamboanga City'),
('Emperatriz Tuason', 'emperatriz.tuason@outlook.com', 'Zamboanga City'),
('Engracia Urrutia', 'engracia.urrutia@gmail.com', 'Zamboanga City'),
('Ennodio Villanueva', 'ennodio.villanueva@yahoo.com', 'Zamboanga City'),
('Epifania Abellana', 'epifania.abellana@gmail.com', 'Zamboanga City'),
('Epitacio Bohol', 'epitacio.bohol@outlook.com', 'Zamboanga City'),
('Erlinda Calamba', 'erlinda.calamba@gmail.com', 'Zamboanga City'),
('Ernesta Dumaguete', 'ernesta.dumaguete@yahoo.com', 'Zamboanga City'),
('Escolastica Estrada', 'escolastica.estrada@gmail.com', 'Zamboanga City'),
('Esmeraldo Fernando', 'esmeraldo.fernando@outlook.com', 'Zamboanga City'),
('Esmeralda Gomez', 'esmeralda.gomez@gmail.com', 'Zamboanga City'),
('Esperidion Habagat', 'esperidion.habagat@yahoo.com', 'Zamboanga City'),
('Estanislao Ibarra', 'estanislao.ibarra@gmail.com', 'Zamboanga City'),
('Ester Jacinto', 'ester.jacinto@outlook.com', 'Zamboanga City'),
('Estrella Kiko', 'estrella.kiko@gmail.com', 'Zamboanga City'),
('Etelvina Laguna', 'etelvina.laguna@yahoo.com', 'Zamboanga City'),
('Eufracio Makati', 'eufracio.makati@gmail.com', 'Zamboanga City'),
('Eufrasia Naga', 'eufrasia.naga@outlook.com', 'Zamboanga City'),
('Eulalia Olongapo', 'eulalia.olongapo@gmail.com', 'Zamboanga City'),
('Eulogia Pangasinan', 'eulogia.pangasinan@yahoo.com', 'Zamboanga City'),
('Eunice Quezon', 'eunice.quezon@gmail.com', 'Zamboanga City'),
('Eusebia Rizal', 'eusebia.rizal@outlook.com', 'Zamboanga City'),
('Evangelina Santos', 'evangelina.santos@gmail.com', 'Zamboanga City'),
('Evelyn Tagaytay', 'evelyn.tagaytay@yahoo.com', 'Zamboanga City'),
('Fabian Urdaneta', 'fabian.urdaneta@gmail.com', 'Zamboanga City'),
('Fabiana Vigan', 'fabiana.vigan@outlook.com', 'Zamboanga City'),
('Facundo Wawa', 'facundo.wawa@gmail.com', 'Zamboanga City'),
('Faustina Xiong', 'faustina.xiong@yahoo.com', 'Zamboanga City'),
('Fausto Yusop', 'fausto.yusop@gmail.com', 'Zamboanga City'),
('Federico Zapata', 'federico.zapata@outlook.com', 'Zamboanga City'),
('Feliciana Araneta', 'feliciana.araneta@gmail.com', 'Zamboanga City'),
('Felicidad Binay', 'felicidad.binay@yahoo.com', 'Zamboanga City'),
('Felicisimo Calixto', 'felicisimo.calixto@gmail.com', 'Zamboanga City'),
('Felipa Dizon', 'felipa.dizon@outlook.com', 'Zamboanga City'),
('Felipe Abellana', 'felipe.abellana@gmail.com', 'Zamboanga City'),
('Felisa Bohol', 'felisa.bohol@yahoo.com', 'Zamboanga City'),
('Felix Calamba', 'felix.calamba@gmail.com', 'Zamboanga City'),
('Ferdinand Dumaguete', 'ferdinand.dumaguete@outlook.com', 'Zamboanga City'),
('Fermina Estrada', 'fermina.estrada@gmail.com', 'Zamboanga City'),
('Fernanda Fernando', 'fernanda.fernando@yahoo.com', 'Zamboanga City'),
('Fidela Gomez', 'fidela.gomez@gmail.com', 'Zamboanga City'),
('Fidelino Habagat', 'fidelino.habagat@outlook.com', 'Zamboanga City'),
('Filemon Ibarra', 'filemon.ibarra@gmail.com', 'Zamboanga City'),
('Filomeno Jacinto', 'filomeno.jacinto@yahoo.com', 'Zamboanga City'),
('Flaviano Kiko', 'flaviano.kiko@gmail.com', 'Zamboanga City'),
('Florentina Laguna', 'florentina.laguna@outlook.com', 'Zamboanga City'),
('Florinda Makati', 'florinda.makati@gmail.com', 'Zamboanga City'),
('Floripe Naga', 'floripe.naga@yahoo.com', 'Zamboanga City'),
('Fortunata Olongapo', 'fortunata.olongapo@gmail.com', 'Zamboanga City'),
('Fortunato Pangasinan', 'fortunato.pangasinan@outlook.com', 'Zamboanga City'),
('Francisca Quezon', 'francisca.quezon@gmail.com', 'Zamboanga City'),
('Fructuoso Rizal', 'fructuoso.rizal@yahoo.com', 'Zamboanga City'),
('Fulgencio Santos', 'fulgencio.santos@gmail.com', 'Zamboanga City'),
('Gabriela Tagaytay', 'gabriela.tagaytay@outlook.com', 'Zamboanga City'),
('Gaudencia Urdaneta', 'gaudencia.urdaneta@gmail.com', 'Zamboanga City'),
('Genoveva Vigan', 'genoveva.vigan@yahoo.com', 'Zamboanga City'),
('Gervasio Wawa', 'gervasio.wawa@gmail.com', 'Zamboanga City'),
('Gertrudes Xiong', 'gertrudes.xiong@outlook.com', 'Zamboanga City'),
('Gilda Yusop', 'gilda.yusop@gmail.com', 'Zamboanga City'),
('Gloria Zapata', 'gloria.zapata@yahoo.com', 'Zamboanga City'),
('Gloriosa Araneta', 'gloriosa.araneta@gmail.com', 'Zamboanga City'),
('Godofredo Binay', 'godofredo.binay@outlook.com', 'Zamboanga City'),
('Graciana Calixto', 'graciana.calixto@gmail.com', 'Zamboanga City'),
('Gregoria Dizon', 'gregoria.dizon@yahoo.com', 'Zamboanga City'),
('Griselda Estrada', 'griselda.estrada@gmail.com', 'Zamboanga City'),
('Guadalupe Fernando', 'guadalupe.fernando@outlook.com', 'Zamboanga City'),
('Guillermina Gomez', 'guillermina.gomez@gmail.com', 'Zamboanga City'),
('Gumersindo Habagat', 'gumersindo.habagat@yahoo.com', 'Zamboanga City'),
('Gustavo Ibarra', 'gustavo.ibarra@gmail.com', 'Zamboanga City'),
('Heliodoro Jacinto', 'heliodoro.jacinto@outlook.com', 'Zamboanga City'),
('Hermenegildo Kiko', 'hermenegildo.kiko@gmail.com', 'Zamboanga City'),
('Herminia Laguna', 'herminia.laguna@yahoo.com', 'Zamboanga City'),
('Higinio Makati', 'higinio.makati@gmail.com', 'Zamboanga City'),
('Hilarion Naga', 'hilarion.naga@outlook.com', 'Zamboanga City'),
('Hilda Olongapo', 'hilda.olongapo@gmail.com', 'Zamboanga City'),
('Honorata Pangasinan', 'honorata.pangasinan@yahoo.com', 'Zamboanga City'),
('Horacio Quezon', 'horacio.quezon@gmail.com', 'Zamboanga City'),
('Hortencia Rizal', 'hortencia.rizal@outlook.com', 'Zamboanga City'),

-- Additional Filipino Names - Other PH Cities (901-1100)
('Ibarra Santos', 'ibarra.santos@gmail.com', 'Cebu City'),
('Ignacia Reyes', 'ignacia.reyes@yahoo.com', 'Davao City'),
('Ildefonso Cruz', 'ildefonso.cruz@gmail.com', 'Manila'),
('Imelda Mendoza', 'imelda.mendoza@outlook.com', 'Quezon City'),
('Inocencia Garcia', 'inocencia.garcia@gmail.com', 'Makati'),
('Ireneo Fernandez', 'ireneo.fernandez@yahoo.com', 'Pasig'),
('Irma Torres', 'irma.torres@gmail.com', 'Taguig'),
('Isaac Ramos', 'isaac.ramos@outlook.com', 'Iloilo City'),
('Isabel Dela Cruz', 'isabel.delacruz@gmail.com', 'Bacolod'),
('Isabelita Villanueva', 'isabelita.villanueva@yahoo.com', 'Cagayan de Oro'),
('Isaias Aquino', 'isaias.aquino@gmail.com', 'General Santos'),
('Ismael Tan', 'ismael.tan@outlook.com', 'Baguio'),
('Ivar Lopez', 'ivar.lopez@gmail.com', 'Cebu City'),
('Jacinta Lim', 'jacinta.lim@yahoo.com', 'Davao City'),
('Jaime Ong', 'jaime.ong@gmail.com', 'Angeles City'),
('Januario Sy', 'januario.sy@outlook.com', 'San Fernando'),
('Jerardo Chua', 'jerardo.chua@gmail.com', 'Lipa'),
('Jesusa Ang', 'jesusa.ang@yahoo.com', 'Batangas City'),
('Joaquin Co', 'joaquin.co@gmail.com', 'Lucena'),
('Joel Dy', 'joel.dy@outlook.com', 'Tagaytay'),
('Josefa Yap', 'josefa.yap@gmail.com', 'Dagupan'),
('Josue Tam', 'josue.tam@yahoo.com', 'Vigan'),
('Jovita Chung', 'jovita.chung@gmail.com', 'Antipolo'),
('Juan Lee', 'juan.lee@outlook.com', 'Caloocan'),
('Juana Wu', 'juana.wu@gmail.com', 'Parañaque'),
('Juanita Chan', 'juanita.chan@yahoo.com', 'Las Piñas'),
('Julian Tiu', 'julian.tiu@gmail.com', 'Mandaluyong'),
('Juliana Uy', 'juliana.uy@outlook.com', 'San Juan'),
('Julio Yu', 'julio.yu@gmail.com', 'Marikina'),
('Justo Ngo', 'justo.ngo@yahoo.com', 'Valenzuela'),
('Ladislao Bautista', 'ladislao.bautista@gmail.com', 'Cebu City'),
('Laureano Pascual', 'laureano.pascual@outlook.com', 'Davao City'),
('Laurencio Santiago', 'laurencio.santiago@gmail.com', 'Manila'),
('Lázaro Rivera', 'lazaro.rivera@yahoo.com', 'Quezon City'),
('Leandro Castro', 'leandro.castro@gmail.com', 'Makati'),
('Leonarda Dimaculangan', 'leonarda.dimaculangan@outlook.com', 'Pasig'),
('Leoncia Manalo', 'leoncia.manalo@gmail.com', 'Taguig'),
('Leoncio Soriano', 'leoncio.soriano@yahoo.com', 'Iloilo City'),
('Leonides Mercado', 'leonides.mercado@gmail.com', 'Bacolod'),
('Leonila Navarro', 'leonila.navarro@outlook.com', 'Cagayan de Oro'),
('Leonora Jimenez', 'leonora.jimenez@gmail.com', 'General Santos'),
('Leopoldina Peralta', 'leopoldina.peralta@yahoo.com', 'Baguio'),
('Leopoldo Medina', 'leopoldo.medina@gmail.com', 'Cebu City'),
('Librada Aguilar', 'librada.aguilar@outlook.com', 'Davao City'),
('Librado Flores', 'librado.flores@gmail.com', 'Angeles City'),
('Liceria Domingo', 'liceria.domingo@yahoo.com', 'San Fernando'),
('Lidia Salazar', 'lidia.salazar@gmail.com', 'Lipa'),
('Lorenzo Luna', 'lorenzo.luna@outlook.com', 'Batangas City'),
('Loreto Espinosa', 'loreto.espinosa@gmail.com', 'Lucena'),
('Lorenza Magno', 'lorenza.magno@yahoo.com', 'Tagaytay'),
('Lourdes Hernandez', 'lourdes.hernandez@gmail.com', 'Dagupan'),
('Lucas Valdez', 'lucas.valdez@outlook.com', 'Vigan'),
('Luciana Ocampo', 'luciana.ocampo@gmail.com', 'Antipolo'),
('Luciano Robles', 'luciano.robles@yahoo.com', 'Caloocan'),
('Lucila Castillo', 'lucila.castillo@gmail.com', 'Parañaque'),
('Lucinda Morales', 'lucinda.morales@outlook.com', 'Las Piñas'),
('Lucio Ignacio', 'lucio.ignacio@gmail.com', 'Mandaluyong'),
('Lucrecia Tolentino', 'lucrecia.tolentino@yahoo.com', 'San Juan'),
('Ludovico Sebastian', 'ludovico.sebastian@gmail.com', 'Marikina'),
('Luis Velasco', 'luis.velasco@outlook.com', 'Valenzuela'),

-- More Filipino Names - Zamboanga City (938-1050)
('Macario Marquez', 'macario.marquez@gmail.com', 'Zamboanga City'),
('Madalena Salvador', 'madalena.salvador@yahoo.com', 'Zamboanga City'),
('Magdalena Padilla', 'magdalena.padilla@gmail.com', 'Zamboanga City'),
('Mamerto Miranda', 'mamerto.miranda@outlook.com', 'Zamboanga City'),
('Manuela Gutierrez', 'manuela.gutierrez@gmail.com', 'Zamboanga City'),
('Marcelina Magsaysay', 'marcelina.magsaysay@yahoo.com', 'Zamboanga City'),
('Marcelino Franco', 'marcelino.franco@gmail.com', 'Zamboanga City'),
('Marcelo Sarmiento', 'marcelo.sarmiento@outlook.com', 'Zamboanga City'),
('Marciana Perez', 'marciana.perez@gmail.com', 'Zamboanga City'),
('Marciano Rosales', 'marciano.rosales@yahoo.com', 'Zamboanga City'),
('Marco Abella', 'marco.abella@gmail.com', 'Zamboanga City'),
('Marcos Buenaventura', 'marcos.buenaventura@outlook.com', 'Zamboanga City'),
('Margarito Concepcion', 'margarito.concepcion@gmail.com', 'Zamboanga City'),
('Maria Delgado', 'maria.delgado123@yahoo.com', 'Zamboanga City'),
('Mariana Enriquez', 'mariana.enriquez@gmail.com', 'Zamboanga City'),
('Mariano Fajardo', 'mariano.fajardo@outlook.com', 'Zamboanga City'),
('Marina Galang', 'marina.galang@gmail.com', 'Zamboanga City'),
('Marino Hidalgo', 'marino.hidalgo@yahoo.com', 'Zamboanga City'),
('Mario Imperial', 'mario.imperial@gmail.com', 'Zamboanga City'),
('Marita Jacinto', 'marita.jacinto@outlook.com', 'Zamboanga City'),
('Martina Kapunan', 'martina.kapunan@gmail.com', 'Zamboanga City'),
('Martin Lacson', 'martin.lacson@yahoo.com', 'Zamboanga City'),
('Mateo Macapagal', 'mateo.macapagal@gmail.com', 'Zamboanga City'),
('Matilde Nakpil', 'matilde.nakpil@outlook.com', 'Zamboanga City'),
('Mauricio Ongpin', 'mauricio.ongpin@gmail.com', 'Zamboanga City'),
('Maxima Palma', 'maxima.palma@yahoo.com', 'Zamboanga City'),
('Maximiano Quijano', 'maximiano.quijano@gmail.com', 'Zamboanga City'),
('Maximino Razon', 'maximino.razon@outlook.com', 'Zamboanga City'),
('Medardo Sotto', 'medardo.sotto@gmail.com', 'Zamboanga City'),
('Melanio Tanco', 'melanio.tanco@yahoo.com', 'Zamboanga City'),
('Melchor Ubaldo', 'melchor.ubaldo@gmail.com', 'Zamboanga City'),
('Melecia Vargas', 'melecia.vargas@outlook.com', 'Zamboanga City'),
('Mercedes Yulo', 'mercedes.yulo@gmail.com', 'Zamboanga City'),
('Miguel Zamora', 'miguel.zamora@yahoo.com', 'Zamboanga City'),
('Modesta Abaya', 'modesta.abaya@gmail.com', 'Zamboanga City'),
('Modesto Bacani', 'modesto.bacani@outlook.com', 'Zamboanga City'),
('Monica Cabrera', 'monica.cabrera@gmail.com', 'Zamboanga City'),
('Narciso Dalisay', 'narciso.dalisay@yahoo.com', 'Zamboanga City'),
('Natalia Escoda', 'natalia.escoda@gmail.com', 'Zamboanga City'),
('Natalio Fontanilla', 'natalio.fontanilla@outlook.com', 'Zamboanga City'),
('Nazaria Gonzaga', 'nazaria.gonzaga@gmail.com', 'Zamboanga City'),
('Nazario Halili', 'nazario.halili@yahoo.com', 'Zamboanga City'),
('Nemesio Ilagan', 'nemesio.ilagan@gmail.com', 'Zamboanga City'),
('Nerio Javier', 'nerio.javier@outlook.com', 'Zamboanga City'),
('Nestor Katigbak', 'nestor.katigbak@gmail.com', 'Zamboanga City'),
('Nicanor Laurel', 'nicanor.laurel@yahoo.com', 'Zamboanga City'),
('Nicolas Madrigal', 'nicolas.madrigal@gmail.com', 'Zamboanga City'),
('Nicolasa Natividad', 'nicolasa.natividad@outlook.com', 'Zamboanga City'),
('Nicomedes Osmena', 'nicomedes.osmena@gmail.com', 'Zamboanga City'),
('Nicostrato Pangilinan', 'nicostrato.pangilinan@yahoo.com', 'Zamboanga City'),
('Noemi Quezon', 'noemi.quezon@gmail.com', 'Zamboanga City'),
('Norberto Recto', 'norberto.recto@outlook.com', 'Zamboanga City'),
('Norma Sison', 'norma.sison@gmail.com', 'Zamboanga City'),
('Obdulia Tantoco', 'obdulia.tantoco@yahoo.com', 'Zamboanga City'),
('Octavio Urquiola', 'octavio.urquiola@gmail.com', 'Zamboanga City'),
('Olegario Villamor', 'olegario.villamor@outlook.com', 'Zamboanga City'),
('Olimpia Wenceslao', 'olimpia.wenceslao@gmail.com', 'Zamboanga City'),
('Olimpio Yabut', 'olimpio.yabut@yahoo.com', 'Zamboanga City'),
('Onofre Zobel', 'onofre.zobel@gmail.com', 'Zamboanga City'),
('Oreste Aglipay', 'oreste.aglipay@outlook.com', 'Zamboanga City'),
('Orosia Bonifacio', 'orosia.bonifacio@gmail.com', 'Zamboanga City'),
('Oscar Cojuangco', 'oscar.cojuangco@yahoo.com', 'Zamboanga City'),
('Osmundo Diokno', 'osmundo.diokno@gmail.com', 'Zamboanga City'),
('Oswaldo Escudero', 'oswaldo.escudero@outlook.com', 'Zamboanga City'),
('Pablo Feliciano', 'pablo.feliciano@gmail.com', 'Zamboanga City'),
('Paciencia Gorospe', 'paciencia.gorospe@yahoo.com', 'Zamboanga City'),
('Pacifico Herrera', 'pacifico.herrera@gmail.com', 'Zamboanga City'),
('Palemon Inting', 'palemon.inting@outlook.com', 'Zamboanga City'),
('Pancracio Jocson', 'pancracio.jocson@gmail.com', 'Zamboanga City'),
('Panfilo Kalaw', 'panfilo.kalaw@yahoo.com', 'Zamboanga City'),
('Pantaleon Lorenzo', 'pantaleon.lorenzo@gmail.com', 'Zamboanga City'),
('Pascasio Macaraig', 'pascasio.macaraig@outlook.com', 'Zamboanga City'),
('Pascual Nepomuceno', 'pascual.nepomuceno@gmail.com', 'Zamboanga City'),
('Pastor Olivares', 'pastor.olivares@yahoo.com', 'Zamboanga City'),
('Patricia Pimentel', 'patricia.pimentel@gmail.com', 'Zamboanga City'),
('Patricio Quintos', 'patricio.quintos@outlook.com', 'Zamboanga City'),
('Paula Romualdez', 'paula.romualdez@gmail.com', 'Zamboanga City'),
('Paulina Salonga', 'paulina.salonga@yahoo.com', 'Zamboanga City'),
('Paulino Trinidad', 'paulino.trinidad@gmail.com', 'Zamboanga City'),
('Pedro Ungson', 'pedro.ungson@outlook.com', 'Zamboanga City'),
('Pelagia Valera', 'pelagia.valera@gmail.com', 'Zamboanga City'),
('Peregrino Wenceslao', 'peregrino.wenceslao@yahoo.com', 'Zamboanga City'),
('Perpetua Ysip', 'perpetua.ysip@gmail.com', 'Zamboanga City'),
('Petra Zarate', 'petra.zarate@outlook.com', 'Zamboanga City'),
('Petronila Abad', 'petronila.abad@gmail.com', 'Zamboanga City'),
('Petrona Bello', 'petrona.bello@yahoo.com', 'Zamboanga City'),
('Pia Carino', 'pia.carino@gmail.com', 'Zamboanga City'),
('Pío Dacquel', 'pio.dacquel@outlook.com', 'Zamboanga City'),
('Placido Evidente', 'placido.evidente@gmail.com', 'Zamboanga City'),
('Policarpo Faustino', 'policarpo.faustino@yahoo.com', 'Zamboanga City'),
('Porfirio Gatchalian', 'porfirio.gatchalian@gmail.com', 'Zamboanga City'),
('Potenciano Hontiveros', 'potenciano.hontiveros@outlook.com', 'Zamboanga City'),
('Preciosa Inchausti', 'preciosa.inchausti@gmail.com', 'Zamboanga City'),
('Priscila Jalandoni', 'priscila.jalandoni@yahoo.com', 'Zamboanga City'),
('Prisco Kasilag', 'prisco.kasilag@gmail.com', 'Zamboanga City'),
('Procopio Legarda', 'procopio.legarda@outlook.com', 'Zamboanga City'),
('Prudencia Maceda', 'prudencia.maceda@gmail.com', 'Zamboanga City'),
('Prudencio Nakpil', 'prudencio.nakpil@yahoo.com', 'Zamboanga City'),
('Querubina Ongpin', 'querubina.ongpin@gmail.com', 'Zamboanga City'),
('Quirina Palanca', 'quirina.palanca@outlook.com', 'Zamboanga City'),
('Quirino Quimpo', 'quirino.quimpo@gmail.com', 'Zamboanga City'),
('Rafael Reyson', 'rafael.reyson@yahoo.com', 'Zamboanga City'),
('Rafaela Syjuco', 'rafaela.syjuco@gmail.com', 'Zamboanga City'),
('Raimundo Tuason', 'raimundo.tuason@outlook.com', 'Zamboanga City'),
('Ramon Urrutia', 'ramon.urrutia@gmail.com', 'Zamboanga City'),
('Ramona Villanueva', 'ramona.villanueva@yahoo.com', 'Zamboanga City'),
('Ranalio Abellana', 'ranalio.abellana@gmail.com', 'Zamboanga City'),
('Raquel Bohol', 'raquel.bohol@outlook.com', 'Zamboanga City'),
('Raymundo Calamba', 'raymundo.calamba@gmail.com', 'Zamboanga City'),
('Rebecca Dumaguete', 'rebecca.dumaguete@yahoo.com', 'Zamboanga City'),
('Regina Estrada', 'regina.estrada@gmail.com', 'Zamboanga City'),
('Reginaldo Fernando', 'reginaldo.fernando@outlook.com', 'Zamboanga City'),

-- More Pet Names - Zamboanga City (1051-1100)
('Sprout Alegre', 'sprout.alegre@gmail.com', 'Zamboanga City'),
('Seedling Banaag', 'seedling.banaag@yahoo.com', 'Zamboanga City'),
('Acorn Catalan', 'acorn.catalan@gmail.com', 'Zamboanga City'),
('Pinecone Dayao', 'pinecone.dayao@outlook.com', 'Zamboanga City'),
('Twig Encabo', 'twig.encabo@gmail.com', 'Zamboanga City'),
('Branch Flores', 'branch.flores@yahoo.com', 'Zamboanga City'),
('Timber Guevara', 'timber.guevara@gmail.com', 'Zamboanga City'),
('Grove Hechanova', 'grove.hechanova@outlook.com', 'Zamboanga City'),
('Forest Ildefonso', 'forest.ildefonso@gmail.com', 'Zamboanga City'),
('Woods Jongco', 'woods.jongco@yahoo.com', 'Zamboanga City'),
('Meadow Kho', 'meadow.kho@gmail.com', 'Zamboanga City'),
('Prairie Lacuata', 'prairie.lacuata@outlook.com', 'Zamboanga City'),
('Savanna Macalalad', 'savanna.macalalad@gmail.com', 'Zamboanga City'),
('Delta Naldo', 'delta.naldo@yahoo.com', 'Zamboanga City'),
('River Oledan', 'river.oledan@gmail.com', 'Zamboanga City'),
('Stream Pagaduan', 'stream.pagaduan@outlook.com', 'Zamboanga City'),
('Creek Quiogue', 'creek.quiogue@gmail.com', 'Zamboanga City'),
('Brook Rondilla', 'brook.rondilla@yahoo.com', 'Zamboanga City'),
('Pond Sarte', 'pond.sarte@gmail.com', 'Zamboanga City'),
('Lake Tanco', 'lake.tanco@outlook.com', 'Zamboanga City'),
('Ocean Urbiztondo', 'ocean.urbiztondo@gmail.com', 'Zamboanga City'),
('Wave Villarama', 'wave.villarama@yahoo.com', 'Zamboanga City'),
('Tide Walung', 'tide.walung@gmail.com', 'Zamboanga City'),
('Coral Yadao', 'coral.yadao@outlook.com', 'Zamboanga City'),
('Shell Zapanta', 'shell.zapanta@gmail.com', 'Zamboanga City'),
('Pearl Alegre', 'pearl.alegre@yahoo.com', 'Zamboanga City'),
('Amber Banaag', 'amber.banaag@gmail.com', 'Zamboanga City'),
('Ruby Catalan', 'ruby.catalan@outlook.com', 'Zamboanga City'),
('Sapphire Dayao', 'sapphire.dayao@gmail.com', 'Zamboanga City'),
('Emerald Encabo', 'emerald.encabo@yahoo.com', 'Zamboanga City'),
('Diamond Flores', 'diamond.flores@gmail.com', 'Zamboanga City'),
('Jade Guevara', 'jade.guevara@outlook.com', 'Zamboanga City'),
('Opal Hechanova', 'opal.hechanova@gmail.com', 'Zamboanga City'),
('Topaz Ildefonso', 'topaz.ildefonso@yahoo.com', 'Zamboanga City'),
('Garnet Jongco', 'garnet.jongco@gmail.com', 'Zamboanga City'),
('Onyx Kho', 'onyx.kho@outlook.com', 'Zamboanga City'),
('Quartz Lacuata', 'quartz.lacuata@gmail.com', 'Zamboanga City'),
('Crystal Macalalad', 'crystal.macalalad@yahoo.com', 'Zamboanga City'),
('Gem Naldo', 'gem.naldo@gmail.com', 'Zamboanga City'),
('Jewel Oledan', 'jewel.oledan@outlook.com', 'Zamboanga City'),
('Stone Pagaduan', 'stone.pagaduan@gmail.com', 'Zamboanga City'),
('Rock Quiogue', 'rock.quiogue@yahoo.com', 'Zamboanga City'),
('Marble Rondilla', 'marble.rondilla@gmail.com', 'Zamboanga City'),
('Granite Sarte', 'granite.sarte@outlook.com', 'Zamboanga City'),
('Slate Tanco', 'slate.tanco@gmail.com', 'Zamboanga City'),
('Cobble Urbiztondo', 'cobble.urbiztondo@yahoo.com', 'Zamboanga City'),
('Flint Villarama', 'flint.villarama@gmail.com', 'Zamboanga City'),
('Clay Walung', 'clay.walung@outlook.com', 'Zamboanga City'),
('Sand Yadao', 'sand.yadao@gmail.com', 'Zamboanga City'),
('Dust Zapanta', 'dust.zapanta@yahoo.com', 'Zamboanga City'),
('Pebble Quintos', 'pebble.quintos@gmail.com', 'Zamboanga City');

GO

-- Verify count and distribution
SELECT COUNT(*) AS TotalCustomers FROM Customers;

SELECT city, COUNT(*) AS Count, 
       CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Customers) AS DECIMAL(5,2)) AS Percentage
FROM Customers 
GROUP BY city
ORDER BY Count DESC;

PRINT '✅ 1100 Customers inserted successfully!';
GO
