-- =====================================================
-- CRUMBEAR CAKE MANAGEMENT SYSTEM - CAKES SEED DATA
-- 100 Realistic Cake Records for a Home Bakery
-- Prices in Philippine Peso (₱300-500)
-- =====================================================

USE CrumbearDB;
GO

-- Clear existing cakes (will cascade to designs/reviews)
DELETE FROM Reviews;
DELETE FROM CakeDesigns;
DELETE FROM Cakes;
GO

-- Reset identity
DBCC CHECKIDENT ('Cakes', RESEED, 0);
GO

-- =====================================================
-- INSERT 100 CAKES
-- =====================================================

INSERT INTO Cakes (cake_name, flavor, frosting, size, base_price, availability) VALUES
-- Single-tier classics (1-20)
('Classic Vanilla Dream', 'Vanilla', 'Buttercream', '6 inch', 350.00, 1),
('Choco Fudge Delight', 'Chocolate', 'Chocolate Ganache', '6 inch', 380.00, 1),
('Ube Cream Cake', 'Ube', 'Whipped Cream', '6 inch', 420.00, 1),
('Mango Cheesecake', 'Mango', 'Cream Cheese', '8 inch', 450.00, 1),
('Red Velvet Classic', 'Red Velvet', 'Cream Cheese', '6 inch', 400.00, 1),
('Mocha Swirl', 'Mocha', 'Buttercream', '6 inch', 360.00, 1),
('Strawberry Bliss', 'Strawberry', 'Whipped Cream', '6 inch', 390.00, 1),
('Caramel Banana Cake', 'Banana', 'Caramel Drizzle', '6 inch', 370.00, 1),
('Lemon Zest Cake', 'Lemon', 'Cream Cheese', '6 inch', 340.00, 1),
('Dark Choco Truffle', 'Dark Chocolate', 'Chocolate Ganache', '6 inch', 420.00, 1),
('Cookies and Cream', 'Cookies & Cream', 'Buttercream', '6 inch', 380.00, 1),
('Pandan Layer Cake', 'Pandan', 'Coconut Cream', '6 inch', 360.00, 1),
('Carrot Walnut Cake', 'Carrot', 'Cream Cheese', '8 inch', 400.00, 1),
('Triple Chocolate', 'Chocolate', 'Chocolate Fudge', '6 inch', 430.00, 1),
('Coconut Pandan Swirl', 'Pandan Coconut', 'Buttercream', '6 inch', 350.00, 1),
('Blueberry Cheesecake', 'Blueberry', 'Cream Cheese', '6 inch', 450.00, 1),
('Coffee Crunch Cake', 'Coffee', 'Mocha Buttercream', '6 inch', 380.00, 1),
('Vanilla Bean Supreme', 'French Vanilla', 'Swiss Meringue', '6 inch', 400.00, 1),
('Dulce de Leche Cake', 'Caramel', 'Dulce de Leche', '6 inch', 410.00, 1),
('Black Forest Classic', 'Chocolate Cherry', 'Whipped Cream', '8 inch', 480.00, 1),

-- Single-tier continued (21-40)
('Matcha Green Tea', 'Matcha', 'White Chocolate', '6 inch', 420.00, 1),
('Funfetti Birthday', 'Vanilla Sprinkle', 'Buttercream', '6 inch', 350.00, 1),
('Salted Caramel Choco', 'Chocolate', 'Salted Caramel', '6 inch', 390.00, 1),
('Butter Pecan Cake', 'Butter Pecan', 'Buttercream', '6 inch', 370.00, 1),
('Raspberry Lemon', 'Lemon Raspberry', 'Cream Cheese', '6 inch', 400.00, 1),
('Pistachio Rose', 'Pistachio', 'Rosewater Buttercream', '6 inch', 450.00, 1),
('Chocolate Orange', 'Orange Chocolate', 'Chocolate Ganache', '6 inch', 380.00, 1),
('Yema Cake', 'Yema', 'Yema Frosting', '6 inch', 340.00, 1),
('Buko Pandan', 'Buko Pandan', 'Whipped Cream', '6 inch', 360.00, 1),
('Marble Swirl Cake', 'Vanilla Chocolate', 'Buttercream', '6 inch', 350.00, 1),
('Honey Almond Cake', 'Almond', 'Honey Buttercream', '6 inch', 400.00, 1),
('Strawberry Shortcake', 'Vanilla', 'Whipped Cream', '6 inch', 380.00, 0),
('Sans Rival Cake', 'Cashew Meringue', 'Buttercream', '8 inch', 500.00, 1),
('Ube Macapuno', 'Ube Macapuno', 'Ube Buttercream', '6 inch', 430.00, 1),
('Moist Choco Cake', 'Chocolate', 'Chocolate Buttercream', '6 inch', 360.00, 1),
('Calamansi Cake', 'Calamansi', 'Cream Cheese', '6 inch', 350.00, 1),
('Peanut Butter Cup', 'Chocolate Peanut', 'Peanut Butter Frosting', '6 inch', 390.00, 1),
('Espresso Cake', 'Espresso', 'Mocha Buttercream', '6 inch', 380.00, 1),
('Burnt Basque Cheesecake', 'Cheesecake', 'None', '6 inch', 450.00, 1),
('Chiffon Orange', 'Orange Chiffon', 'Whipped Cream', '8 inch', 340.00, 1),

-- Single-tier continued (41-60)
('Brazo de Mercedes', 'Custard Meringue', 'Meringue', '8 inch', 380.00, 1),
('Sylvanas Cake', 'Cashew', 'Buttercream', '6 inch', 420.00, 1),
('Tiramisu Cake', 'Coffee Mascarpone', 'Mascarpone Cream', '6 inch', 480.00, 1),
('Bibingka Cake', 'Bibingka', 'Coconut Cream', '6 inch', 350.00, 1),
('Champagne Cake', 'Champagne Vanilla', 'Swiss Meringue', '6 inch', 470.00, 0),
('Mango Float Cake', 'Mango Graham', 'Whipped Cream', '8 inch', 400.00, 1),
('Leche Flan Cake', 'Leche Flan', 'Caramel', '6 inch', 420.00, 1),
('Ube Leche Flan', 'Ube', 'Leche Flan Topping', '6 inch', 450.00, 1),
('Vanilla Caramel', 'Vanilla', 'Caramel Buttercream', '6 inch', 360.00, 1),
('Hazelnut Praline', 'Hazelnut', 'Praline Buttercream', '6 inch', 430.00, 1),
('White Chocolate Raspberry', 'White Chocolate', 'Raspberry Buttercream', '6 inch', 400.00, 1),
('Taro Cake', 'Taro', 'Taro Buttercream', '6 inch', 380.00, 1),
('Chocolate Mint', 'Mint Chocolate', 'Mint Buttercream', '6 inch', 370.00, 1),
('Snickers Cake', 'Chocolate Caramel', 'Peanut Buttercream', '6 inch', 410.00, 1),
('Nutella Dream', 'Chocolate Hazelnut', 'Nutella Frosting', '6 inch', 400.00, 1),
('Apple Cinnamon', 'Apple Spice', 'Cinnamon Buttercream', '6 inch', 360.00, 1),
('Tres Leches Cake', 'Tres Leches', 'Whipped Cream', '8 inch', 380.00, 1),
('Earl Grey Lavender', 'Earl Grey', 'Lavender Buttercream', '6 inch', 420.00, 0),
('Churros Cake', 'Cinnamon Sugar', 'Dulce de Leche', '6 inch', 370.00, 1),
('S''mores Cake', 'Chocolate Graham', 'Toasted Marshmallow', '6 inch', 390.00, 1),

-- Single-tier continued (61-80)
('Avocado Cake', 'Avocado', 'Avocado Buttercream', '6 inch', 380.00, 1),
('Cheese Roll Cake', 'Cheese', 'Cheese Frosting', '8 inch', 350.00, 1),
('Purple Yam Cake', 'Purple Yam', 'Ube Buttercream', '6 inch', 400.00, 1),
('Chocolate Lava Cake', 'Dark Chocolate', 'Chocolate Ganache', '6 inch', 430.00, 1),
('Confetti Vanilla', 'Vanilla', 'Rainbow Buttercream', '6 inch', 340.00, 1),
('Speculoos Cake', 'Biscoff', 'Biscoff Buttercream', '6 inch', 410.00, 1),
('Chocolate Raspberry', 'Chocolate', 'Raspberry Ganache', '6 inch', 420.00, 1),
('Passion Fruit Cake', 'Passion Fruit', 'Passion Fruit Curd', '6 inch', 440.00, 1),
('Strawberry Matcha', 'Matcha', 'Strawberry Cream', '6 inch', 400.00, 1),
('Lemon Poppy Seed', 'Lemon Poppy', 'Lemon Glaze', '6 inch', 350.00, 1),
('Banana Nutella', 'Banana', 'Nutella Frosting', '6 inch', 380.00, 1),
('Ferrero Rocher Cake', 'Chocolate Hazelnut', 'Ferrero Buttercream', '6 inch', 480.00, 1),
('Oreo Cheesecake', 'Oreo', 'Cream Cheese', '6 inch', 420.00, 1),
('Toblerone Cake', 'Chocolate Honey', 'Toblerone Ganache', '6 inch', 450.00, 0),
('Caramel Macchiato', 'Coffee Caramel', 'Caramel Drizzle', '6 inch', 390.00, 1),
('Honeycomb Crunch', 'Honey', 'Honeycomb Buttercream', '6 inch', 370.00, 1),
('Cotton Candy Cake', 'Vanilla', 'Cotton Candy Buttercream', '6 inch', 360.00, 1),
('Coconut Lime', 'Coconut Lime', 'Coconut Buttercream', '6 inch', 380.00, 1),
('German Chocolate', 'Chocolate', 'Coconut Pecan', '8 inch', 450.00, 1),
('Salted Egg Cake', 'Salted Egg', 'Salted Egg Frosting', '6 inch', 420.00, 1),

-- Single-tier final batch (81-90)
('Blueberry Lemon', 'Lemon', 'Blueberry Compote', '6 inch', 390.00, 1),
('Chocolate Covered Strawberry', 'Chocolate', 'Strawberry Buttercream', '6 inch', 400.00, 1),
('Vanilla Almond', 'Almond Vanilla', 'Almond Buttercream', '6 inch', 360.00, 1),
('Milo Cake', 'Milo', 'Milo Buttercream', '6 inch', 340.00, 1),
('Lotus Biscoff Dream', 'Biscoff', 'Caramelized Biscoff', '6 inch', 430.00, 1),
('Ube Cheese Pandesal', 'Ube Cheese', 'Cream Cheese', '6 inch', 380.00, 0),
('Classic Butter Cake', 'Butter', 'Vanilla Buttercream', '6 inch', 300.00, 1),
('Choco Butternut', 'Chocolate', 'Butternut Crumble', '6 inch', 350.00, 1),
('Peach Mango Cake', 'Peach Mango', 'Whipped Cream', '8 inch', 420.00, 1),
('Chocolate Overload', 'Triple Chocolate', 'Chocolate Ganache', '6 inch', 460.00, 1),

-- Multi-tier cakes (91-100) - Only 10 entries with layers
('Wedding White 2-Tier', 'Vanilla', 'Fondant', '8 inch + 6 inch', 490.00, 1),
('Celebration Choco Tower', 'Chocolate', 'Chocolate Buttercream', '8 inch + 6 inch', 500.00, 1),
('Birthday Bonanza 2-Layer', 'Funfetti', 'Buttercream', '8 inch + 6 inch', 480.00, 1),
('Elegant Ube Stack', 'Ube', 'Ube Buttercream', '8 inch + 6 inch', 500.00, 1),
('Red Velvet Grandeur', 'Red Velvet', 'Cream Cheese', '10 inch + 8 inch', 500.00, 0),
('Triple Decker Mocha', 'Mocha', 'Mocha Buttercream', '8 inch + 6 inch + 4 inch', 500.00, 1),
('Anniversary Rose Tower', 'Vanilla Rose', 'Swiss Meringue', '8 inch + 6 inch', 490.00, 1),
('3-Tier Chocolate Dream', 'Dark Chocolate', 'Chocolate Ganache', '10 inch + 8 inch + 6 inch', 500.00, 1),
('Pastel Rainbow Stack', 'Rainbow Vanilla', 'Buttercream', '8 inch + 6 inch', 480.00, 1),
('Grand Caramel Tower', 'Caramel', 'Salted Caramel', '8 inch + 6 inch + 4 inch', 500.00, 1),

-- Additional batch (101-130)
('Honey Butter Cake', 'Honey Butter', 'Honey Glaze', '6 inch', 340.00, 1),
('Quezo Real Cake', 'Cheese', 'Cheese Buttercream', '6 inch', 380.00, 1),
('Choco Mallows', 'Chocolate', 'Marshmallow Frosting', '6 inch', 350.00, 1),
('Strawberry Vanilla Swirl', 'Strawberry Vanilla', 'Strawberry Buttercream', '6 inch', 370.00, 1),
('Classic Ensaymada Cake', 'Butter Cheese', 'Buttercream', '8 inch', 360.00, 1),
('Puto Bumbong Cake', 'Purple Rice', 'Coconut Buttercream', '6 inch', 400.00, 1),
('Cassava Cake Fusion', 'Cassava', 'Macapuno Cream', '8 inch', 350.00, 1),
('Mais Con Yelo Cake', 'Sweet Corn', 'Milk Cream', '6 inch', 330.00, 1),
('Halo-Halo Inspired', 'Mixed Fruit', 'Ube Buttercream', '6 inch', 420.00, 1),
('Mango Graham Float', 'Mango', 'Graham Cream', '8 inch', 380.00, 1),
('Choco Banana Split', 'Banana Chocolate', 'Whipped Cream', '6 inch', 360.00, 1),
('Vanilla Birthday Special', 'Vanilla', 'Rainbow Buttercream', '6 inch', 320.00, 1),
('Decadent Brownie Cake', 'Fudge Brownie', 'Chocolate Ganache', '6 inch', 430.00, 1),
('Rocky Road Cake', 'Chocolate Nut', 'Marshmallow Fudge', '6 inch', 400.00, 1),
('Strawberry Fields', 'Fresh Strawberry', 'Strawberry Cream', '6 inch', 410.00, 1),
('Pinoy Fiesta Cake', 'Ube Cheese', 'Ube Cream Cheese', '8 inch', 450.00, 1),
('Choco Caramel Drip', 'Chocolate', 'Caramel Drip', '6 inch', 380.00, 1),
('Creamy Leche Cake', 'Milk', 'Condensed Milk Frosting', '6 inch', 340.00, 1),
('Almond Joy Cake', 'Coconut Almond', 'Chocolate Coconut', '6 inch', 420.00, 1),
('Mango Tango', 'Fresh Mango', 'Mango Buttercream', '6 inch', 400.00, 1),
('Purple Velvet', 'Ube', 'Cream Cheese', '6 inch', 390.00, 1),
('Choco Peanut Blast', 'Chocolate Peanut', 'Peanut Butter Drip', '6 inch', 370.00, 1),
('Goldilocks Style', 'Mocha', 'Mocha Frosting', '8 inch', 350.00, 1),
('Polvoron Cake', 'Polvoron', 'Powdered Milk Frosting', '6 inch', 360.00, 1),
('Cinnamon Roll Cake', 'Cinnamon', 'Cream Cheese Glaze', '6 inch', 380.00, 1),
('Tsokolate Tablea', 'Tablea Chocolate', 'Tablea Ganache', '6 inch', 410.00, 1),
('Keso Cake Deluxe', 'Cheddar Cheese', 'Cheese Frosting', '6 inch', 370.00, 0),
('Banana Walnut Bread Cake', 'Banana Walnut', 'Cream Cheese', '8 inch', 390.00, 1),
('Pinipig Crunch Cake', 'Vanilla', 'Pinipig Buttercream', '6 inch', 340.00, 1),
('Choco Chip Cookie Cake', 'Cookie Dough', 'Vanilla Buttercream', '6 inch', 380.00, 1),

-- Additional batch (131-160)
('Strawberry Cheesecake Swirl', 'Strawberry Cheese', 'Cream Cheese', '6 inch', 450.00, 1),
('Classic Mocha Roll', 'Mocha', 'Mocha Cream', '8 inch', 340.00, 1),
('Pandan Buko Delight', 'Pandan', 'Buko Cream', '6 inch', 360.00, 1),
('Choco Lava Supreme', 'Molten Chocolate', 'Chocolate Shell', '6 inch', 440.00, 1),
('Cafe Americano Cake', 'Coffee', 'Espresso Buttercream', '6 inch', 390.00, 1),
('Vanilla Bean Dream', 'Madagascar Vanilla', 'Vanilla Bean Frosting', '6 inch', 420.00, 1),
('Coconut Macaroon Cake', 'Coconut', 'Toasted Coconut', '6 inch', 350.00, 1),
('Double Dutch Cake', 'Double Chocolate', 'Fudge Frosting', '6 inch', 400.00, 1),
('Langka Cake', 'Jackfruit', 'Coconut Cream', '6 inch', 370.00, 1),
('Custard Cream Cake', 'Custard', 'Vanilla Custard', '6 inch', 360.00, 1),
('Atis Ice Cream Cake', 'Sugar Apple', 'Whipped Cream', '6 inch', 400.00, 0),
('Suman Cake', 'Sticky Rice', 'Coconut Caramel', '8 inch', 380.00, 1),
('Champorado Cake', 'Chocolate Rice', 'Condensed Milk', '6 inch', 350.00, 1),
('Kakanin Fusion', 'Pandan Coconut', 'Latik Topping', '6 inch', 370.00, 1),
('Maja Blanca Cake', 'Coconut Corn', 'Coconut Cream', '8 inch', 340.00, 1),
('Ginataan Cake', 'Coconut Sweet Potato', 'Gata Frosting', '6 inch', 360.00, 1),
('Turon Cake', 'Banana Jackfruit', 'Caramel Glaze', '6 inch', 350.00, 1),
('Sapin Sapin Cake', 'Layered Ube', 'Coconut Cream', '8 inch', 420.00, 1),
('Kutsinta Cake', 'Brown Sugar', 'Coconut Topping', '6 inch', 310.00, 1),
('Pichi Pichi Cake', 'Cassava Coconut', 'Grated Coconut', '6 inch', 330.00, 1),
('Espasol Cake', 'Toasted Rice', 'Coconut Cream', '6 inch', 340.00, 1),
('Palitaw Cake', 'Sesame Coconut', 'Sesame Topping', '6 inch', 320.00, 1),
('Biko Cake', 'Sweet Rice', 'Latik Drizzle', '8 inch', 350.00, 1),
('Sorbetes Cake', 'Cheese Ube', 'Cheese Ube Swirl', '6 inch', 400.00, 1),
('Dirty Ice Cream Style', 'Vanilla Ube Cheese', 'Triple Swirl', '6 inch', 410.00, 1),
('Pan de Coco Cake', 'Coconut Bread', 'Sweet Coconut Filling', '6 inch', 330.00, 1),
('Ensaimada Cheese Cake', 'Buttery Cheese', 'Cheese Buttercream', '6 inch', 380.00, 1),
('Monay Cake', 'Bread', 'Butter Glaze', '6 inch', 300.00, 1),
('Spanish Bread Cake', 'Buttery Crumb', 'Sugar Crust', '6 inch', 320.00, 1),
('Pandesal Cake', 'Soft Bread', 'Butter Frosting', '6 inch', 310.00, 1),

-- Additional batch (161-200)
('White Forest Cake', 'White Chocolate Cherry', 'Whipped Cream', '8 inch', 470.00, 1),
('Boston Cream Cake', 'Custard Filled', 'Chocolate Glaze', '6 inch', 420.00, 1),
('New York Cheesecake', 'Classic Cheesecake', 'Sour Cream Topping', '8 inch', 480.00, 1),
('Japanese Cotton Cake', 'Light Sponge', 'Dusted Sugar', '6 inch', 350.00, 1),
('Korean Cream Cake', 'Light Vanilla', 'Fresh Cream', '6 inch', 400.00, 1),
('Hokkaido Cake', 'Milk', 'Hokkaido Cream', '6 inch', 420.00, 1),
('Swiss Roll Log', 'Vanilla', 'Whipped Cream', '8 inch', 340.00, 1),
('Opera Cake', 'Coffee Almond', 'Coffee Ganache', '8 inch', 480.00, 1),
('Sachertorte', 'Chocolate Apricot', 'Chocolate Glaze', '8 inch', 490.00, 0),
('Genoise Sponge Cake', 'Light Sponge', 'Fruit Cream', '6 inch', 360.00, 1),
('Chiffon Cake Classic', 'Orange Chiffon', 'Light Glaze', '8 inch', 330.00, 1),
('Pound Cake Deluxe', 'Butter Pound', 'Lemon Glaze', '8 inch', 350.00, 1),
('Angel Food Cake', 'Light Vanilla', 'Berry Compote', '8 inch', 340.00, 1),
('Devils Food Cake', 'Dark Chocolate', 'Chocolate Fudge', '6 inch', 400.00, 1),
('Upside Down Pineapple', 'Pineapple', 'Caramel Glaze', '8 inch', 380.00, 1),
('Rum Cake', 'Rum Soaked', 'Rum Glaze', '6 inch', 420.00, 1),
('Fruit Cake Classic', 'Mixed Fruit Nut', 'Sugar Glaze', '8 inch', 400.00, 1),
('Bolo Rei', 'Portuguese Fruit', 'Candied Fruit', '8 inch', 450.00, 1),
('Tres Leches Deluxe', 'Three Milk', 'Cinnamon Cream', '8 inch', 390.00, 1),
('Dulce de Leche Dream', 'Caramel', 'Dulce Drizzle', '6 inch', 410.00, 1),
('Alfajor Cake', 'Dulce de Leche', 'Coconut Coating', '6 inch', 400.00, 1),
('Churro Cake Fiesta', 'Cinnamon Sugar', 'Chocolate Dip', '6 inch', 380.00, 1),
('Mexican Chocolate', 'Spiced Chocolate', 'Chili Chocolate', '6 inch', 420.00, 1),
('Coconut Tres Leches', 'Coconut Milk', 'Toasted Coconut', '8 inch', 400.00, 1),
('Guava Cheesecake', 'Guava', 'Cream Cheese', '6 inch', 430.00, 1),
('Passionfruit Mousse', 'Passion Fruit', 'Mousse Topping', '6 inch', 440.00, 1),
('Tropical Mango Mousse', 'Mango', 'Mango Mousse', '6 inch', 420.00, 1),
('Coco Pandan Supreme', 'Pandan Coconut', 'Pandan Cream', '6 inch', 370.00, 1),
('Banana Foster Cake', 'Banana Rum', 'Caramel Banana', '6 inch', 400.00, 1),
('Pecan Praline Cake', 'Pecan', 'Praline Frosting', '6 inch', 450.00, 1),
('Walnut Maple Cake', 'Maple Walnut', 'Maple Buttercream', '6 inch', 420.00, 1),
('Pistachio Delight', 'Pistachio', 'Pistachio Cream', '6 inch', 460.00, 1),
('Macadamia White Choco', 'Macadamia', 'White Chocolate', '6 inch', 480.00, 1),
('Cashew Crunch Cake', 'Cashew', 'Cashew Praline', '6 inch', 430.00, 1),
('Almond Amaretto', 'Almond Amaretto', 'Amaretto Glaze', '6 inch', 440.00, 1),
('Hazelnut Gianduja', 'Hazelnut', 'Gianduja Cream', '6 inch', 470.00, 1),
('Peanut Brittle Cake', 'Peanut', 'Peanut Brittle Top', '6 inch', 380.00, 1),
('Chestnut Cake', 'Chestnut', 'Chestnut Cream', '6 inch', 460.00, 0),
('Walnut Date Cake', 'Date Walnut', 'Toffee Sauce', '6 inch', 390.00, 1),
('Fig Honey Cake', 'Fig', 'Honey Mascarpone', '6 inch', 450.00, 1),

-- Additional batch (201-250)
('Ginger Molasses Cake', 'Ginger', 'Cream Cheese', '6 inch', 360.00, 1),
('Pumpkin Spice Cake', 'Pumpkin', 'Cinnamon Cream Cheese', '6 inch', 380.00, 1),
('Sweet Potato Cake', 'Camote', 'Brown Butter Frosting', '6 inch', 350.00, 1),
('Squash Cake', 'Kalabasa', 'Coconut Cream', '6 inch', 330.00, 1),
('Zucchini Cake', 'Zucchini Spice', 'Cream Cheese', '6 inch', 360.00, 1),
('Beetroot Cake', 'Beetroot Chocolate', 'Chocolate Ganache', '6 inch', 400.00, 1),
('Lavender Honey Cake', 'Lavender', 'Honey Buttercream', '6 inch', 430.00, 1),
('Rose Pistachio', 'Rose', 'Pistachio Cream', '6 inch', 450.00, 1),
('Jasmine Tea Cake', 'Jasmine', 'Light Cream', '6 inch', 400.00, 1),
('Chamomile Cake', 'Chamomile', 'Honey Glaze', '6 inch', 380.00, 1),
('Oolong Tea Cake', 'Oolong', 'Milk Tea Cream', '6 inch', 410.00, 1),
('Thai Tea Cake', 'Thai Tea', 'Condensed Milk', '6 inch', 390.00, 1),
('Taro Milk Tea Cake', 'Taro Milk Tea', 'Taro Cream', '6 inch', 420.00, 1),
('Brown Sugar Boba Cake', 'Brown Sugar', 'Boba Topping', '6 inch', 430.00, 1),
('Wintermelon Cake', 'Wintermelon', 'Light Cream', '6 inch', 370.00, 1),
('Yakult Cake', 'Yakult', 'Yogurt Frosting', '6 inch', 360.00, 1),
('Calpico Cake', 'Calpis', 'Citrus Cream', '6 inch', 370.00, 1),
('Melon Pan Cake', 'Melon Bread', 'Cookie Crust', '6 inch', 380.00, 1),
('Dorayaki Cake', 'Red Bean', 'Honey Glaze', '6 inch', 400.00, 1),
('Mochi Cake', 'Mochi', 'Kinako Dusting', '6 inch', 420.00, 1),
('Matcha Azuki', 'Matcha Red Bean', 'Matcha Cream', '6 inch', 440.00, 1),
('Hojicha Cake', 'Roasted Green Tea', 'Hojicha Cream', '6 inch', 430.00, 1),
('Kinako Cake', 'Roasted Soybean', 'Black Sesame Cream', '6 inch', 400.00, 1),
('Black Sesame Cake', 'Black Sesame', 'Sesame Buttercream', '6 inch', 410.00, 1),
('Goma Cake', 'White Sesame', 'Sesame Praline', '6 inch', 390.00, 1),
('Yuzu Cake', 'Yuzu Citrus', 'Yuzu Glaze', '6 inch', 450.00, 1),
('Sudachi Cake', 'Sudachi Lime', 'Citrus Cream', '6 inch', 440.00, 0),
('Ume Cake', 'Plum', 'Plum Glaze', '6 inch', 420.00, 1),
('Sakura Cake', 'Cherry Blossom', 'Pink Buttercream', '6 inch', 460.00, 1),
('Momiji Cake', 'Maple Leaf', 'Autumn Spice Cream', '6 inch', 400.00, 1),
('Ichigo Shortcake', 'Japanese Strawberry', 'Fresh Cream', '6 inch', 450.00, 1),
('Mango Sticky Rice Cake', 'Mango Rice', 'Coconut Cream', '6 inch', 400.00, 1),
('Pandan Kaya Cake', 'Pandan', 'Kaya Cream', '6 inch', 380.00, 1),
('Ondeh Ondeh Cake', 'Pandan Gula Melaka', 'Coconut Cream', '6 inch', 410.00, 1),
('Kueh Lapis Cake', 'Spiced Layer', 'None', '8 inch', 480.00, 1),
('Bandung Cake', 'Rose Syrup', 'Condensed Milk', '6 inch', 360.00, 1),
('Cendol Cake', 'Pandan Gula Melaka', 'Coconut Cream', '6 inch', 400.00, 1),
('Chendol Cake', 'Green Jelly', 'Gula Melaka Drizzle', '6 inch', 390.00, 1),
('Pulut Hitam Cake', 'Black Glutinous', 'Coconut Cream', '6 inch', 370.00, 1),
('Bubur Cha Cha Cake', 'Mixed Yam', 'Coconut Milk', '6 inch', 380.00, 1),
('Sago Gula Melaka', 'Sago', 'Palm Sugar Syrup', '6 inch', 350.00, 1),
('Tapai Cake', 'Fermented Rice', 'Sweet Rice Cream', '6 inch', 360.00, 1),
('Lepat Pisang Cake', 'Banana Sticky', 'Coconut Cream', '6 inch', 340.00, 1),
('Getuk Cake', 'Cassava', 'Grated Coconut', '6 inch', 320.00, 1),
('Klepon Cake', 'Pandan Coconut', 'Palm Sugar Center', '6 inch', 400.00, 1),
('Onde Onde Cake', 'Sesame Ball', 'Red Bean Filling', '6 inch', 410.00, 1),
('Apam Balik Cake', 'Peanut Pancake', 'Sweet Corn', '6 inch', 350.00, 1),
('Roti Canai Cake', 'Buttery Flatbread', 'Condensed Milk', '6 inch', 360.00, 1),
('Kaya Toast Cake', 'Kaya', 'Butter Toast', '6 inch', 370.00, 1),
('Nasi Lemak Cake', 'Coconut Rice', 'Pandan Cream', '6 inch', 380.00, 1),

-- Additional batch (251-300)
('Durian Cake', 'Durian', 'Durian Cream', '6 inch', 500.00, 1),
('Durian Cheesecake', 'Durian', 'Cream Cheese', '6 inch', 500.00, 1),
('Musang King Cake', 'Premium Durian', 'Durian Mousse', '6 inch', 500.00, 0),
('Cempedak Cake', 'Cempedak', 'Coconut Cream', '6 inch', 420.00, 1),
('Rambutan Cake', 'Rambutan', 'Lychee Cream', '6 inch', 400.00, 1),
('Lychee Rose Cake', 'Lychee', 'Rose Cream', '6 inch', 430.00, 1),
('Longan Cake', 'Longan', 'Light Cream', '6 inch', 380.00, 1),
('Dragon Fruit Cake', 'Pink Pitaya', 'Vanilla Cream', '6 inch', 420.00, 1),
('Soursop Cake', 'Guyabano', 'Cream Cheese', '6 inch', 400.00, 1),
('Papaya Cake', 'Papaya', 'Lime Cream', '6 inch', 350.00, 1),
('Watermelon Cake', 'Watermelon', 'Mint Cream', '6 inch', 370.00, 1),
('Honeydew Cake', 'Honeydew Melon', 'Light Cream', '6 inch', 380.00, 1),
('Cantaloupe Cake', 'Cantaloupe', 'Vanilla Cream', '6 inch', 360.00, 1),
('Starfruit Cake', 'Balimbing', 'Citrus Glaze', '6 inch', 370.00, 1),
('Santol Cake', 'Santol', 'Coconut Cream', '6 inch', 350.00, 1),
('Chico Cake', 'Chico', 'Caramel Cream', '6 inch', 360.00, 1),
('Siniguelas Cake', 'Spanish Plum', 'Sour Cream', '6 inch', 340.00, 1),
('Tamarind Cake', 'Sampalok', 'Tamarind Glaze', '6 inch', 370.00, 1),
('Green Mango Cake', 'Unripe Mango', 'Bagoong Cream', '6 inch', 380.00, 1),
('Calamansi Cheesecake', 'Calamansi', 'Cream Cheese', '6 inch', 420.00, 1),
('Dalandan Cake', 'Native Orange', 'Orange Cream', '6 inch', 360.00, 1),
('Pomelo Cake', 'Suha', 'Light Cream', '6 inch', 380.00, 1),
('Avocado Cheesecake', 'Avocado', 'Cream Cheese', '6 inch', 450.00, 1),
('Coconut Panna Cotta Cake', 'Coconut', 'Panna Cotta Layer', '6 inch', 440.00, 1),
('Mango Panna Cotta', 'Mango', 'Panna Cotta Cream', '6 inch', 430.00, 1),
('Strawberry Panna Cotta', 'Strawberry', 'Italian Cream', '6 inch', 420.00, 1),
('Mixed Berry Panna Cotta', 'Mixed Berry', 'Berry Compote', '6 inch', 450.00, 1),
('Blueberry Yogurt Cake', 'Blueberry', 'Greek Yogurt', '6 inch', 400.00, 1),
('Raspberry Yogurt Cake', 'Raspberry', 'Yogurt Frosting', '6 inch', 410.00, 1),
('Cranberry Orange Cake', 'Cranberry Orange', 'Orange Glaze', '6 inch', 390.00, 1),

-- Additional batch (301-350)
('Blackberry Vanilla', 'Blackberry', 'Vanilla Cream', '6 inch', 420.00, 1),
('Mulberry Cake', 'Mulberry', 'Light Cream', '6 inch', 400.00, 1),
('Elderflower Cake', 'Elderflower', 'Lemon Cream', '6 inch', 430.00, 1),
('Hibiscus Cake', 'Hibiscus', 'Raspberry Cream', '6 inch', 410.00, 1),
('Butterfly Pea Cake', 'Blue Ternate', 'Lemon Cream', '6 inch', 400.00, 1),
('Moringa Cake', 'Malunggay', 'Coconut Cream', '6 inch', 370.00, 1),
('Turmeric Ginger Cake', 'Turmeric', 'Ginger Glaze', '6 inch', 360.00, 1),
('Charcoal Cake', 'Activated Charcoal', 'White Cream', '6 inch', 420.00, 1),
('Galaxy Mirror Cake', 'Vanilla', 'Mirror Glaze', '6 inch', 480.00, 1),
('Geode Cake', 'Vanilla', 'Rock Candy', '6 inch', 500.00, 1),
('Fault Line Cake', 'Chocolate', 'Buttercream', '6 inch', 450.00, 1),
('Drip Cake Classic', 'Vanilla', 'Chocolate Drip', '6 inch', 400.00, 1),
('Naked Cake Rustic', 'Vanilla', 'Light Buttercream', '6 inch', 350.00, 1),
('Semi Naked Cake', 'Chocolate', 'Thin Buttercream', '6 inch', 370.00, 1),
('Ombre Cake Pink', 'Vanilla', 'Pink Ombre Buttercream', '6 inch', 420.00, 1),
('Ombre Cake Blue', 'Vanilla', 'Blue Ombre Buttercream', '6 inch', 420.00, 1),
('Watercolor Cake', 'Vanilla', 'Watercolor Buttercream', '6 inch', 450.00, 1),
('Painted Cake Floral', 'Vanilla', 'Hand Painted Buttercream', '6 inch', 480.00, 1),
('Buttercream Flower Cake', 'Vanilla', 'Flower Piping', '6 inch', 470.00, 1),
('Korean Flower Cake', 'Vanilla', 'Bean Paste Flowers', '6 inch', 500.00, 1),
('Lambeth Cake', 'Vanilla', 'Royal Icing', '8 inch', 490.00, 1),
('Vintage Lace Cake', 'Vanilla', 'Lace Fondant', '6 inch', 460.00, 1),
('Ruffles Cake', 'Vanilla', 'Ruffle Buttercream', '6 inch', 440.00, 1),
('Rosette Cake', 'Vanilla', 'Rosette Piping', '6 inch', 400.00, 1),
('Swirl Cake', 'Chocolate Vanilla', 'Two Tone Swirl', '6 inch', 380.00, 1),
('Number Cake 1', 'Vanilla', 'Cream Fruit', '10 inch', 450.00, 1),
('Number Cake 2', 'Chocolate', 'Cream Fruit', '10 inch', 460.00, 1),
('Letter Cake A', 'Vanilla', 'Fresh Cream', '10 inch', 450.00, 0),
('Heart Shaped Cake', 'Red Velvet', 'Cream Cheese', '8 inch', 420.00, 1),
('Star Shaped Cake', 'Vanilla', 'Gold Buttercream', '8 inch', 440.00, 1),

-- Additional batch (351-370) - More multi-tier/special
('Premier Wedding Cake', 'Vanilla', 'White Fondant', '10 inch + 8 inch', 500.00, 1),
('Rustic Wedding Stack', 'Naked Vanilla', 'Berry Drip', '8 inch + 6 inch', 490.00, 1),
('Floral Wedding Tower', 'Champagne', 'Swiss Meringue', '8 inch + 6 inch', 500.00, 1),
('Gold Elegance 2-Tier', 'Vanilla', 'Gold Buttercream', '8 inch + 6 inch', 500.00, 1),
('Rose Gold Stack', 'Strawberry', 'Rose Gold Drip', '8 inch + 6 inch', 490.00, 1),
('Marble Effect Tower', 'Vanilla', 'Marble Fondant', '8 inch + 6 inch', 500.00, 1),
('Minimalist White Stack', 'Vanilla', 'Smooth White', '8 inch + 6 inch', 480.00, 1),
('Blush Pink Tower', 'Vanilla Rose', 'Blush Buttercream', '8 inch + 6 inch', 490.00, 1),
('Navy Gold Stack', 'Chocolate', 'Navy Gold Accent', '8 inch + 6 inch', 500.00, 1),
('Greenery Wedding Cake', 'Lemon', 'Eucalyptus Decor', '8 inch + 6 inch', 490.00, 1),
('Bohemian Wedding Stack', 'Carrot', 'Cream Cheese', '8 inch + 6 inch', 480.00, 1),
('Vintage Romance Tower', 'Earl Grey', 'Lavender Cream', '8 inch + 6 inch', 500.00, 1),
('Garden Party 3-Tier', 'Lemon Elderflower', 'Fresh Cream', '10 inch + 8 inch + 6 inch', 500.00, 1),
('Grand Celebration Tower', 'Chocolate', 'Ganache Drip', '10 inch + 8 inch + 6 inch', 500.00, 1),
('Royal 3-Tier', 'Vanilla', 'Gold Fondant', '10 inch + 8 inch + 6 inch', 500.00, 1),
('Princess Castle Cake', 'Pink Vanilla', 'Pink Buttercream', '8 inch + 6 inch', 500.00, 1),
('Superhero Stack', 'Chocolate', 'Fondant', '8 inch + 6 inch', 480.00, 1),
('Unicorn Tower', 'Rainbow', 'Pastel Buttercream', '8 inch + 6 inch', 490.00, 1),
('Dinosaur Stack', 'Vanilla', 'Green Buttercream', '8 inch + 6 inch', 470.00, 1),
('Safari Tower', 'Banana', 'Jungle Theme', '8 inch + 6 inch', 480.00, 1),

-- Final batch (371-400) - Completing to 400
('Simple Vanilla Round', 'Vanilla', 'Buttercream', '6 inch', 300.00, 1),
('Basic Chocolate Cake', 'Chocolate', 'Chocolate Frosting', '6 inch', 320.00, 1),
('Plain Butter Cake', 'Butter', 'Sugar Glaze', '6 inch', 300.00, 1),
('Simple Mocha Cake', 'Mocha', 'Mocha Frosting', '6 inch', 330.00, 1),
('Basic Ube Cake', 'Ube', 'Ube Frosting', '6 inch', 350.00, 1),
('Simple Cheese Cake', 'Cheese', 'Cheese Topping', '6 inch', 340.00, 1),
('Plain Pandan Cake', 'Pandan', 'Coconut Cream', '6 inch', 320.00, 1),
('Basic Strawberry Cake', 'Strawberry', 'Strawberry Cream', '6 inch', 350.00, 1),
('Simple Mango Cake', 'Mango', 'Mango Cream', '6 inch', 360.00, 1),
('Plain Caramel Cake', 'Caramel', 'Caramel Drizzle', '6 inch', 340.00, 1),
('Basic Red Velvet', 'Red Velvet', 'Cream Cheese', '6 inch', 370.00, 1),
('Simple Coffee Cake', 'Coffee', 'Coffee Frosting', '6 inch', 330.00, 1),
('Plain Lemon Cake', 'Lemon', 'Lemon Glaze', '6 inch', 310.00, 1),
('Basic Banana Cake', 'Banana', 'Vanilla Frosting', '6 inch', 300.00, 1),
('Simple Coconut Cake', 'Coconut', 'Coconut Frosting', '6 inch', 320.00, 1),
('Plain Carrot Cake', 'Carrot', 'Cream Cheese', '6 inch', 350.00, 1),
('Basic Orange Cake', 'Orange', 'Orange Glaze', '6 inch', 310.00, 1),
('Simple Marble Cake', 'Marble', 'Chocolate Glaze', '6 inch', 320.00, 1),
('Plain White Cake', 'White Vanilla', 'White Frosting', '6 inch', 300.00, 1),
('Basic Funfetti', 'Funfetti', 'Vanilla Buttercream', '6 inch', 330.00, 1),
('Simple Chiffon', 'Chiffon', 'Light Cream', '8 inch', 310.00, 1),
('Plain Sponge Cake', 'Sponge', 'Dusted Sugar', '6 inch', 300.00, 1),
('Basic Pound Cake', 'Pound', 'Butter Glaze', '8 inch', 320.00, 1),
('Simple Angel Cake', 'Angel Food', 'Berry Sauce', '8 inch', 330.00, 1),
('Plain Choco Chip', 'Chocolate Chip', 'Vanilla Cream', '6 inch', 340.00, 1),
('Basic Walnut Cake', 'Walnut', 'Maple Glaze', '6 inch', 350.00, 1),
('Simple Pecan Cake', 'Pecan', 'Caramel Drizzle', '6 inch', 360.00, 1),
('Plain Almond Cake', 'Almond', 'Almond Glaze', '6 inch', 350.00, 1),
('Basic Pistachio', 'Pistachio', 'Pistachio Cream', '6 inch', 400.00, 1),
('Home Style Vanilla', 'Classic Vanilla', 'Simple Buttercream', '6 inch', 300.00, 1),

-- Batch 401-450
('Tita Nene Special', 'Ube Macapuno', 'Ube Cream', '6 inch', 420.00, 1),
('Lola Recipe Cake', 'Butter', 'Classic Buttercream', '6 inch', 310.00, 1),
('Sunday Family Cake', 'Chocolate', 'Fudge Frosting', '8 inch', 380.00, 1),
('Fiesta Celebration', 'Vanilla', 'Colorful Buttercream', '8 inch', 360.00, 1),
('Birthday Girl Pink', 'Strawberry', 'Pink Buttercream', '6 inch', 370.00, 1),
('Birthday Boy Blue', 'Vanilla', 'Blue Buttercream', '6 inch', 370.00, 1),
('Christening White', 'Vanilla', 'White Fondant', '6 inch', 400.00, 1),
('Graduation Cap Cake', 'Chocolate', 'Black Fondant', '6 inch', 420.00, 1),
('Debut Pink Elegance', 'Strawberry Vanilla', 'Blush Pink', '8 inch', 450.00, 1),
('Anniversary Gold', 'Vanilla', 'Gold Accents', '6 inch', 440.00, 1),
('Silver Wedding Cake', 'White Vanilla', 'Silver Buttercream', '8 inch', 460.00, 1),
('Retirement Celebration', 'Mocha', 'Coffee Buttercream', '8 inch', 380.00, 1),
('Promotion Party Cake', 'Chocolate', 'Gold Drip', '6 inch', 400.00, 1),
('Housewarming Cake', 'Vanilla', 'Pastel Buttercream', '6 inch', 350.00, 1),
('Baby Shower Pink', 'Strawberry', 'Baby Pink Cream', '6 inch', 380.00, 1),
('Baby Shower Blue', 'Blueberry', 'Baby Blue Cream', '6 inch', 380.00, 1),
('Gender Reveal Cake', 'Vanilla', 'Hidden Color Center', '6 inch', 420.00, 1),
('Welcome Home Cake', 'Chocolate', 'Warm Buttercream', '6 inch', 350.00, 1),
('Get Well Soon Cake', 'Lemon', 'Cheerful Yellow', '6 inch', 340.00, 1),
('Thank You Cake', 'Vanilla', 'Floral Buttercream', '6 inch', 360.00, 1),
('Sorry Cake', 'Chocolate', 'Heart Decor', '6 inch', 350.00, 1),
('Congratulations Cake', 'Funfetti', 'Celebration Buttercream', '6 inch', 370.00, 1),
('Good Luck Cake', 'Vanilla', 'Green Buttercream', '6 inch', 340.00, 1),
('Miss You Cake', 'Red Velvet', 'Heart Cream Cheese', '6 inch', 390.00, 1),
('Thinking of You', 'Lavender', 'Purple Buttercream', '6 inch', 400.00, 1),
('Just Because Cake', 'Chocolate', 'Simple Ganache', '6 inch', 360.00, 1),
('Love You Cake', 'Red Velvet', 'Red Heart Decor', '6 inch', 400.00, 1),
('Best Mom Cake', 'Vanilla Rose', 'Pink Rose Piping', '6 inch', 420.00, 1),
('Best Dad Cake', 'Chocolate', 'Blue Buttercream', '6 inch', 380.00, 1),
('Teachers Day Cake', 'Apple Cinnamon', 'Apple Decor', '6 inch', 360.00, 1),

-- Batch 451-500
('Office Party Cake', 'Mocha', 'Coffee Theme', '8 inch', 400.00, 1),
('Team Building Cake', 'Chocolate Vanilla', 'Marble Swirl', '8 inch', 380.00, 1),
('Company Anniversary', 'Vanilla', 'Corporate Colors', '8 inch', 450.00, 1),
('Product Launch Cake', 'Chocolate', 'Gold Finish', '8 inch', 470.00, 1),
('Client Appreciation', 'Red Velvet', 'Elegant Finish', '6 inch', 400.00, 1),
('Employee Birthday', 'Funfetti', 'Office Party', '6 inch', 340.00, 1),
('Quarterly Celebration', 'Vanilla', 'Success Theme', '8 inch', 380.00, 1),
('Year End Party Cake', 'Chocolate', 'Festive Decor', '8 inch', 420.00, 1),
('New Year Cake', 'Champagne', 'Gold Sparkle', '6 inch', 450.00, 1),
('Valentines Heart', 'Red Velvet', 'Red Heart Shape', '8 inch', 430.00, 1),
('Easter Bunny Cake', 'Carrot', 'Bunny Decor', '6 inch', 380.00, 1),
('Mothers Day Rose', 'Rose', 'Pink Rose Buttercream', '6 inch', 420.00, 1),
('Fathers Day Classic', 'Chocolate', 'Masculine Design', '6 inch', 380.00, 1),
('Independence Day', 'Vanilla', 'Philippine Flag', '8 inch', 400.00, 1),
('All Saints Day', 'Vanilla', 'White Elegant', '6 inch', 340.00, 1),
('Halloween Orange', 'Orange', 'Pumpkin Decor', '6 inch', 380.00, 0),
('Christmas Red Green', 'Red Velvet', 'Christmas Theme', '8 inch', 450.00, 1),
('Christmas Log Cake', 'Chocolate', 'Yule Log Style', '8 inch', 420.00, 1),
('Noche Buena Cake', 'Ube Cheese', 'Festive Purple', '8 inch', 460.00, 1),
('Media Noche Cake', 'Vanilla', 'Countdown Theme', '8 inch', 400.00, 1),
('Summer Tropical', 'Mango Pineapple', 'Tropical Decor', '6 inch', 390.00, 1),
('Beach Party Cake', 'Coconut', 'Ocean Theme', '6 inch', 380.00, 1),
('Pool Party Blue', 'Blue Velvet', 'Pool Theme', '6 inch', 400.00, 1),
('Garden Party Floral', 'Lemon', 'Fresh Flowers', '6 inch', 420.00, 1),
('Picnic Basket Cake', 'Strawberry', 'Checkered Pattern', '6 inch', 380.00, 1),
('BBQ Party Cake', 'Chocolate', 'BBQ Theme', '6 inch', 360.00, 1),
('Camping Cake', 'Smores', 'Tent Decor', '6 inch', 390.00, 1),
('Road Trip Cake', 'Vanilla', 'Car Theme', '6 inch', 370.00, 1),
('Movie Night Cake', 'Popcorn Caramel', 'Film Reel', '6 inch', 400.00, 1),
('Game Night Cake', 'Chocolate', 'Dice Decor', '6 inch', 370.00, 1),

-- Batch 501-550
('Sports Fan Cake', 'Vanilla', 'Basketball Theme', '6 inch', 380.00, 1),
('Soccer Ball Cake', 'Chocolate', 'Soccer Theme', '6 inch', 400.00, 1),
('Baseball Diamond', 'Vanilla', 'Diamond Shape', '6 inch', 390.00, 1),
('Tennis Court Cake', 'Lemon', 'Green Court', '6 inch', 370.00, 1),
('Golf Course Cake', 'Vanilla', 'Golf Theme', '6 inch', 400.00, 1),
('Swimming Pool Cake', 'Blue', 'Pool Lane', '6 inch', 380.00, 1),
('Yoga Zen Cake', 'Matcha', 'Peaceful Theme', '6 inch', 410.00, 1),
('Gym Fitness Cake', 'Protein Chocolate', 'Dumbbell Decor', '6 inch', 390.00, 1),
('Dance Recital Cake', 'Pink Vanilla', 'Ballet Theme', '6 inch', 420.00, 1),
('Music Note Cake', 'Chocolate', 'Music Theme', '6 inch', 400.00, 1),
('Piano Keys Cake', 'Vanilla Chocolate', 'Piano Design', '8 inch', 450.00, 1),
('Guitar Shape Cake', 'Mocha', 'Guitar Outline', '8 inch', 440.00, 1),
('Artist Palette Cake', 'Rainbow', 'Paint Theme', '6 inch', 410.00, 1),
('Camera Cake', 'Chocolate', 'Camera Shape', '6 inch', 420.00, 1),
('Book Lovers Cake', 'Vanilla', 'Open Book', '8 inch', 400.00, 1),
('Travel Globe Cake', 'Vanilla', 'World Map', '6 inch', 450.00, 1),
('Airplane Cake', 'Vanilla', 'Airplane Theme', '6 inch', 400.00, 1),
('Train Cake', 'Chocolate', 'Train Theme', '6 inch', 390.00, 1),
('Car Lovers Cake', 'Vanilla', 'Sports Car', '6 inch', 420.00, 1),
('Motorcycle Cake', 'Chocolate', 'Biker Theme', '6 inch', 400.00, 1),
('Boat Ship Cake', 'Vanilla', 'Nautical Theme', '6 inch', 410.00, 1),
('Space Rocket Cake', 'Galaxy', 'Space Theme', '6 inch', 450.00, 1),
('Astronaut Cake', 'Vanilla', 'Moon Landing', '6 inch', 440.00, 1),
('Dinosaur Cake', 'Chocolate', 'Dino Theme', '6 inch', 380.00, 1),
('Dragon Cake', 'Red Velvet', 'Dragon Theme', '6 inch', 420.00, 1),
('Mermaid Cake', 'Blue Vanilla', 'Mermaid Tail', '6 inch', 430.00, 1),
('Fairy Garden Cake', 'Vanilla', 'Fairy Theme', '6 inch', 410.00, 1),
('Superhero Cake', 'Chocolate', 'Hero Theme', '6 inch', 400.00, 1),
('Princess Castle', 'Pink Vanilla', 'Castle Theme', '6 inch', 450.00, 1),
('Pirate Ship Cake', 'Chocolate', 'Pirate Theme', '6 inch', 420.00, 1),

-- Batch 551-600
('Robot Cake', 'Silver Vanilla', 'Robot Theme', '6 inch', 400.00, 1),
('Video Game Cake', 'Chocolate', 'Gamer Theme', '6 inch', 390.00, 1),
('Minecraft Cake', 'Chocolate', 'Block Theme', '6 inch', 410.00, 1),
('Pokemon Cake', 'Yellow Vanilla', 'Pikachu Theme', '6 inch', 420.00, 1),
('Hello Kitty Cake', 'Strawberry', 'Kitty Theme', '6 inch', 430.00, 1),
('Doraemon Cake', 'Blue Vanilla', 'Doraemon Theme', '6 inch', 400.00, 1),
('Peppa Pig Cake', 'Pink Vanilla', 'Peppa Theme', '6 inch', 380.00, 1),
('Paw Patrol Cake', 'Vanilla', 'Paw Theme', '6 inch', 390.00, 1),
('Frozen Theme Cake', 'Blue Vanilla', 'Elsa Theme', '6 inch', 440.00, 1),
('Moana Ocean Cake', 'Coconut', 'Ocean Theme', '6 inch', 420.00, 1),
('Lion King Cake', 'Orange Vanilla', 'Safari Theme', '6 inch', 410.00, 1),
('Mickey Mouse Cake', 'Chocolate', 'Mickey Theme', '6 inch', 400.00, 1),
('Minnie Mouse Cake', 'Strawberry', 'Minnie Theme', '6 inch', 400.00, 1),
('Spiderman Cake', 'Red Velvet', 'Spidey Theme', '6 inch', 420.00, 1),
('Batman Cake', 'Dark Chocolate', 'Bat Theme', '6 inch', 410.00, 1),
('Superman Cake', 'Blue Vanilla', 'Super Theme', '6 inch', 400.00, 1),
('Wonder Woman Cake', 'Red Vanilla', 'Amazon Theme', '6 inch', 410.00, 1),
('Avengers Cake', 'Chocolate', 'Marvel Theme', '8 inch', 480.00, 1),
('Star Wars Cake', 'Chocolate', 'Jedi Theme', '6 inch', 450.00, 1),
('Harry Potter Cake', 'Butterbeer', 'Wizard Theme', '6 inch', 460.00, 1),
('BTS Army Cake', 'Purple Ube', 'BTS Theme', '6 inch', 450.00, 1),
('Blackpink Cake', 'Pink Strawberry', 'Blink Theme', '6 inch', 440.00, 1),
('KPop Fan Cake', 'Vanilla', 'Lightstick Theme', '6 inch', 420.00, 1),
('Anime Cake', 'Matcha', 'Anime Theme', '6 inch', 410.00, 1),
('Studio Ghibli Cake', 'Vanilla', 'Totoro Theme', '6 inch', 450.00, 1),
('One Piece Cake', 'Chocolate', 'Pirate Theme', '6 inch', 430.00, 1),
('Naruto Cake', 'Orange Vanilla', 'Ninja Theme', '6 inch', 420.00, 1),
('Demon Slayer Cake', 'Vanilla', 'Anime Theme', '6 inch', 440.00, 1),
('Attack on Titan', 'Chocolate', 'Titan Theme', '6 inch', 430.00, 0),
('Jujutsu Kaisen', 'Dark Chocolate', 'Anime Theme', '6 inch', 440.00, 1),

-- Batch 601-650
('Barbie Pink Dream', 'Pink Vanilla', 'Barbie Theme', '6 inch', 420.00, 1),
('Hot Wheels Cake', 'Chocolate', 'Race Car', '6 inch', 380.00, 1),
('LEGO Block Cake', 'Vanilla', 'LEGO Theme', '6 inch', 400.00, 1),
('Transformers Cake', 'Silver Chocolate', 'Robot Theme', '6 inch', 430.00, 1),
('Nerf Gun Cake', 'Orange Vanilla', 'Nerf Theme', '6 inch', 390.00, 1),
('Squishmallow Cake', 'Pastel Vanilla', 'Squishy Theme', '6 inch', 400.00, 1),
('LOL Surprise Cake', 'Pink Vanilla', 'LOL Theme', '6 inch', 410.00, 1),
('Ryan World Cake', 'Yellow Vanilla', 'Ryan Theme', '6 inch', 380.00, 1),
('Cocomelon Cake', 'Watermelon', 'Melon Theme', '6 inch', 390.00, 1),
('Baby Shark Cake', 'Blue Vanilla', 'Shark Theme', '6 inch', 400.00, 1),
('Bluey Cake', 'Blue Vanilla', 'Bluey Theme', '6 inch', 390.00, 1),
('Daniel Tiger Cake', 'Orange Vanilla', 'Tiger Theme', '6 inch', 370.00, 1),
('Sesame Street Cake', 'Vanilla', 'Elmo Theme', '6 inch', 380.00, 1),
('Dora Explorer Cake', 'Vanilla', 'Explorer Theme', '6 inch', 370.00, 1),
('SpongeBob Cake', 'Yellow Vanilla', 'Bikini Bottom', '6 inch', 400.00, 1),
('Tom and Jerry Cake', 'Chocolate Vanilla', 'Chase Theme', '6 inch', 390.00, 1),
('Looney Tunes Cake', 'Vanilla', 'Cartoon Theme', '6 inch', 380.00, 1),
('Scooby Doo Cake', 'Chocolate', 'Mystery Machine', '6 inch', 400.00, 1),
('Powerpuff Girls Cake', 'Rainbow Vanilla', 'PPG Theme', '6 inch', 410.00, 1),
('Teen Titans Cake', 'Vanilla', 'Titans Theme', '6 inch', 400.00, 1),
('Ninjago Cake', 'Green Vanilla', 'Ninja Theme', '6 inch', 420.00, 1),
('Ben 10 Cake', 'Green Vanilla', 'Omnitrix Theme', '6 inch', 400.00, 1),
('PJ Masks Cake', 'Blue Vanilla', 'Hero Theme', '6 inch', 390.00, 1),
('Trolls Rainbow Cake', 'Rainbow', 'Poppy Theme', '6 inch', 420.00, 1),
('Encanto Mirabel', 'Vanilla', 'Butterfly Theme', '6 inch', 430.00, 1),
('Coco Guitar Cake', 'Chocolate', 'Coco Theme', '6 inch', 410.00, 1),
('Raya Dragon Cake', 'Vanilla', 'Dragon Theme', '6 inch', 440.00, 1),
('Luca Sea Cake', 'Blue Vanilla', 'Sea Monster', '6 inch', 420.00, 1),
('Turning Red Panda', 'Red Vanilla', 'Panda Theme', '6 inch', 430.00, 1),
('Elemental Cake', 'Vanilla', 'Element Theme', '6 inch', 420.00, 1),

-- Batch 651-700
('Construction Cake', 'Yellow Vanilla', 'Builder Theme', '6 inch', 380.00, 1),
('Fireman Cake', 'Red Vanilla', 'Fire Truck', '6 inch', 400.00, 1),
('Police Car Cake', 'Blue Vanilla', 'Police Theme', '6 inch', 390.00, 1),
('Doctor Cake', 'White Vanilla', 'Medical Theme', '6 inch', 370.00, 1),
('Nurse Appreciation', 'White Vanilla', 'Nurse Theme', '6 inch', 380.00, 1),
('Teacher Apple Cake', 'Apple', 'School Theme', '6 inch', 360.00, 1),
('Scientist Cake', 'Vanilla', 'Lab Theme', '6 inch', 400.00, 1),
('Engineer Cake', 'Chocolate', 'Blueprint Theme', '6 inch', 390.00, 1),
('Lawyer Cake', 'Vanilla', 'Justice Theme', '6 inch', 400.00, 1),
('Chef Hat Cake', 'Vanilla', 'Culinary Theme', '6 inch', 410.00, 1),
('Artist Brush Cake', 'Rainbow', 'Art Theme', '6 inch', 420.00, 1),
('Writer Book Cake', 'Vanilla', 'Book Theme', '6 inch', 380.00, 1),
('Photographer Cake', 'Chocolate', 'Camera Theme', '6 inch', 400.00, 1),
('Musician Note Cake', 'Vanilla', 'Music Theme', '6 inch', 390.00, 1),
('Dancer Shoe Cake', 'Pink Vanilla', 'Ballet Shoe', '6 inch', 420.00, 1),
('Pilot Airplane Cake', 'Vanilla', 'Aviation Theme', '6 inch', 430.00, 1),
('Sailor Boat Cake', 'Blue Vanilla', 'Nautical Theme', '6 inch', 400.00, 1),
('Farmer Harvest Cake', 'Carrot', 'Farm Theme', '6 inch', 360.00, 1),
('Gardener Flower Cake', 'Vanilla', 'Garden Theme', '6 inch', 380.00, 1),
('Pet Lover Dog Cake', 'Vanilla', 'Puppy Theme', '6 inch', 390.00, 1),
('Cat Lover Cake', 'Vanilla', 'Kitty Theme', '6 inch', 390.00, 1),
('Bunny Rabbit Cake', 'Carrot', 'Bunny Theme', '6 inch', 370.00, 1),
('Hamster Cake', 'Vanilla', 'Hamster Theme', '6 inch', 360.00, 1),
('Fish Aquarium Cake', 'Blue Vanilla', 'Fish Theme', '6 inch', 400.00, 1),
('Bird Cage Cake', 'Vanilla', 'Bird Theme', '6 inch', 380.00, 1),
('Butterfly Garden', 'Vanilla', 'Butterfly Theme', '6 inch', 410.00, 1),
('Ladybug Cake', 'Red Vanilla', 'Ladybug Theme', '6 inch', 370.00, 1),
('Bee Honeycomb Cake', 'Honey', 'Bee Theme', '6 inch', 390.00, 1),
('Owl Night Cake', 'Chocolate', 'Owl Theme', '6 inch', 400.00, 1),
('Flamingo Pink Cake', 'Pink Vanilla', 'Flamingo Theme', '6 inch', 420.00, 1),

-- Batch 701-750
('Llama Fiesta Cake', 'Vanilla', 'Llama Theme', '6 inch', 410.00, 1),
('Sloth Chill Cake', 'Chocolate', 'Sloth Theme', '6 inch', 390.00, 1),
('Koala Eucalyptus', 'Vanilla', 'Koala Theme', '6 inch', 400.00, 1),
('Panda Bamboo Cake', 'Vanilla', 'Panda Theme', '6 inch', 410.00, 1),
('Elephant Safari', 'Vanilla', 'Elephant Theme', '6 inch', 400.00, 1),
('Giraffe Spots Cake', 'Vanilla', 'Giraffe Theme', '6 inch', 390.00, 1),
('Zebra Stripes Cake', 'Chocolate Vanilla', 'Zebra Theme', '6 inch', 400.00, 1),
('Lion Mane Cake', 'Orange Vanilla', 'Lion Theme', '6 inch', 420.00, 1),
('Tiger Stripes Cake', 'Orange Chocolate', 'Tiger Theme', '6 inch', 410.00, 1),
('Monkey Banana Cake', 'Banana', 'Monkey Theme', '6 inch', 370.00, 1),
('Bear Honey Cake', 'Honey', 'Bear Theme', '6 inch', 380.00, 1),
('Fox Autumn Cake', 'Orange Vanilla', 'Fox Theme', '6 inch', 400.00, 1),
('Deer Forest Cake', 'Vanilla', 'Deer Theme', '6 inch', 390.00, 1),
('Wolf Moon Cake', 'Dark Chocolate', 'Wolf Theme', '6 inch', 420.00, 1),
('Unicorn Magic Cake', 'Rainbow Vanilla', 'Unicorn Theme', '6 inch', 450.00, 1),
('Pegasus Cloud Cake', 'Vanilla', 'Pegasus Theme', '6 inch', 440.00, 1),
('Phoenix Fire Cake', 'Red Orange', 'Phoenix Theme', '6 inch', 460.00, 1),
('Griffin Gold Cake', 'Vanilla', 'Griffin Theme', '6 inch', 450.00, 1),
('Kraken Sea Cake', 'Blue Vanilla', 'Kraken Theme', '6 inch', 430.00, 1),
('Yeti Snow Cake', 'Vanilla', 'Yeti Theme', '6 inch', 400.00, 1),
('Sasquatch Forest', 'Chocolate', 'Bigfoot Theme', '6 inch', 390.00, 0),
('Loch Ness Cake', 'Blue Vanilla', 'Nessie Theme', '6 inch', 410.00, 1),
('Alien Space Cake', 'Green Vanilla', 'UFO Theme', '6 inch', 420.00, 1),
('Zombie Spooky Cake', 'Green Chocolate', 'Zombie Theme', '6 inch', 380.00, 1),
('Vampire Blood Cake', 'Red Velvet', 'Vampire Theme', '6 inch', 400.00, 1),
('Werewolf Moon Cake', 'Chocolate', 'Werewolf Theme', '6 inch', 390.00, 1),
('Witch Cauldron Cake', 'Green Vanilla', 'Witch Theme', '6 inch', 400.00, 1),
('Ghost Boo Cake', 'White Vanilla', 'Ghost Theme', '6 inch', 370.00, 1),
('Skeleton Bones Cake', 'Vanilla', 'Skeleton Theme', '6 inch', 380.00, 1),
('Frankenstein Cake', 'Green Vanilla', 'Monster Theme', '6 inch', 390.00, 1),

-- Batch 751-800
('Mummy Wrap Cake', 'Vanilla', 'Mummy Theme', '6 inch', 380.00, 1),
('Pumpkin Spice Fall', 'Pumpkin', 'Fall Theme', '6 inch', 400.00, 1),
('Autumn Leaves Cake', 'Maple', 'Autumn Theme', '6 inch', 390.00, 1),
('Winter Snowflake', 'Vanilla', 'Winter Theme', '6 inch', 410.00, 1),
('Spring Blossom Cake', 'Cherry Blossom', 'Spring Theme', '6 inch', 420.00, 1),
('Summer Sunshine', 'Lemon', 'Summer Theme', '6 inch', 380.00, 1),
('Rainy Day Cake', 'Blue Vanilla', 'Rain Theme', '6 inch', 360.00, 1),
('Rainbow After Rain', 'Rainbow', 'Rainbow Theme', '6 inch', 400.00, 1),
('Cloudy Sky Cake', 'Vanilla', 'Cloud Theme', '6 inch', 350.00, 1),
('Sunrise Morning Cake', 'Orange Vanilla', 'Sunrise Theme', '6 inch', 380.00, 1),
('Sunset Evening Cake', 'Orange Red', 'Sunset Theme', '6 inch', 390.00, 1),
('Starry Night Cake', 'Dark Blue', 'Stars Theme', '6 inch', 420.00, 1),
('Moon Glow Cake', 'Vanilla', 'Moon Theme', '6 inch', 400.00, 1),
('Galaxy Swirl Cake', 'Galaxy', 'Galaxy Theme', '6 inch', 450.00, 1),
('Nebula Dream Cake', 'Purple Blue', 'Nebula Theme', '6 inch', 440.00, 1),
('Aurora Borealis', 'Green Blue', 'Aurora Theme', '6 inch', 460.00, 1),
('Ocean Wave Cake', 'Blue Vanilla', 'Ocean Theme', '6 inch', 400.00, 1),
('Mountain Peak Cake', 'Vanilla', 'Mountain Theme', '6 inch', 390.00, 1),
('Forest Trees Cake', 'Green Vanilla', 'Forest Theme', '6 inch', 380.00, 1),
('Desert Cactus Cake', 'Vanilla', 'Desert Theme', '6 inch', 370.00, 1),
('Tropical Island Cake', 'Coconut Pineapple', 'Island Theme', '6 inch', 420.00, 1),
('Arctic Ice Cake', 'Vanilla', 'Polar Theme', '6 inch', 400.00, 1),
('Volcano Lava Cake', 'Chocolate Orange', 'Volcano Theme', '6 inch', 430.00, 1),
('Waterfall Blue Cake', 'Blue Vanilla', 'Waterfall Theme', '6 inch', 410.00, 1),
('River Stream Cake', 'Blue Vanilla', 'River Theme', '6 inch', 380.00, 1),
('Lake Calm Cake', 'Blue Vanilla', 'Lake Theme', '6 inch', 370.00, 1),
('Meadow Flower Cake', 'Vanilla', 'Meadow Theme', '6 inch', 390.00, 1),
('Countryside Farm', 'Vanilla', 'Farm Theme', '6 inch', 360.00, 1),
('City Skyline Cake', 'Chocolate', 'City Theme', '6 inch', 420.00, 1),
('Eiffel Tower Cake', 'Vanilla', 'Paris Theme', '6 inch', 450.00, 1),

-- Batch 801-850
('Big Ben London Cake', 'Earl Grey', 'London Theme', '6 inch', 430.00, 1),
('Statue of Liberty', 'Vanilla', 'NYC Theme', '6 inch', 440.00, 1),
('Tokyo Tower Cake', 'Matcha', 'Tokyo Theme', '6 inch', 450.00, 1),
('Sydney Opera Cake', 'Vanilla', 'Sydney Theme', '6 inch', 430.00, 1),
('Santorini Blue Cake', 'Blue Vanilla', 'Greece Theme', '6 inch', 440.00, 1),
('Venice Gondola Cake', 'Vanilla', 'Venice Theme', '6 inch', 450.00, 1),
('Swiss Alps Cake', 'Chocolate', 'Swiss Theme', '6 inch', 420.00, 1),
('Amsterdam Tulip Cake', 'Vanilla', 'Dutch Theme', '6 inch', 410.00, 1),
('Barcelona Art Cake', 'Orange', 'Spanish Theme', '6 inch', 400.00, 1),
('Rome Colosseum Cake', 'Tiramisu', 'Italian Theme', '6 inch', 460.00, 1),
('Cairo Pyramid Cake', 'Vanilla', 'Egyptian Theme', '6 inch', 420.00, 1),
('Dubai Gold Cake', 'Vanilla', 'Dubai Theme', '6 inch', 480.00, 1),
('Bali Paradise Cake', 'Coconut', 'Bali Theme', '6 inch', 400.00, 1),
('Manila Bay Cake', 'Ube', 'Manila Theme', '6 inch', 380.00, 1),
('Palawan Beach Cake', 'Coconut Mango', 'Palawan Theme', '6 inch', 420.00, 1),
('Boracay Sand Cake', 'Vanilla', 'Boracay Theme', '6 inch', 410.00, 1),
('Cebu Lechon Cake', 'Vanilla', 'Cebu Theme', '6 inch', 380.00, 1),
('Baguio Pine Cake', 'Strawberry', 'Baguio Theme', '6 inch', 400.00, 1),
('Tagaytay Fog Cake', 'Coffee', 'Tagaytay Theme', '6 inch', 390.00, 1),
('Vigan Heritage Cake', 'Vanilla', 'Vigan Theme', '6 inch', 370.00, 1),
('Sagada Cloud Cake', 'Vanilla', 'Sagada Theme', '6 inch', 380.00, 1),
('Siargao Surf Cake', 'Coconut', 'Siargao Theme', '6 inch', 420.00, 1),
('Batanes Hills Cake', 'Vanilla', 'Batanes Theme', '6 inch', 400.00, 1),
('Chocolate Hills Cake', 'Chocolate', 'Bohol Theme', '6 inch', 390.00, 1),
('Mayon Volcano Cake', 'Chocolate', 'Bicol Theme', '6 inch', 400.00, 1),
('Taal Lake Cake', 'Blue Vanilla', 'Batangas Theme', '6 inch', 380.00, 1),
('Hundred Islands', 'Vanilla', 'Pangasinan Theme', '6 inch', 390.00, 1),
('La Union Surf Cake', 'Coconut', 'La Union Theme', '6 inch', 400.00, 1),
('Ilocos Sand Dunes', 'Vanilla', 'Ilocos Theme', '6 inch', 380.00, 1),
('Cordillera Rice Cake', 'Vanilla', 'Cordillera Theme', '6 inch', 370.00, 1),

-- Batch 851-900
('Zamboanga Pink Cake', 'Pink Vanilla', 'Zamboanga Theme', '6 inch', 380.00, 1),
('Davao Durian Cake', 'Durian', 'Davao Theme', '6 inch', 500.00, 1),
('Camiguin Lanzones', 'Lanzones', 'Camiguin Theme', '6 inch', 400.00, 1),
('Siquijor Mystery', 'Dark Vanilla', 'Siquijor Theme', '6 inch', 390.00, 0),
('Dumaguete Siliman', 'Vanilla', 'Dumaguete Theme', '6 inch', 370.00, 1),
('Bacolod MassKara', 'Vanilla', 'Bacolod Theme', '6 inch', 400.00, 1),
('Iloilo Dinagyang', 'Chocolate', 'Iloilo Theme', '6 inch', 390.00, 1),
('Aklan Ati-Atihan', 'Vanilla', 'Kalibo Theme', '6 inch', 380.00, 1),
('Legazpi Pili Cake', 'Pili Nut', 'Legazpi Theme', '6 inch', 420.00, 1),
('Naga Pili Special', 'Pili Nut', 'Naga Theme', '6 inch', 410.00, 1),
('Tacloban Moron Cake', 'Chocolate', 'Tacloban Theme', '6 inch', 360.00, 1),
('Ormoc Pineapple', 'Pineapple', 'Ormoc Theme', '6 inch', 380.00, 1),
('General Santos Tuna', 'Vanilla', 'GenSan Theme', '6 inch', 370.00, 1),
('Cagayan de Oro', 'Vanilla', 'CDO Theme', '6 inch', 380.00, 1),
('Bukidnon Pineapple', 'Pineapple', 'Bukidnon Theme', '6 inch', 390.00, 1),
('Marawi Peace Cake', 'Vanilla', 'Marawi Theme', '6 inch', 360.00, 1),
('Cotabato Durian', 'Durian', 'Cotabato Theme', '6 inch', 480.00, 1),
('Tawi-Tawi Sea Cake', 'Coconut', 'Tawi-Tawi Theme', '6 inch', 400.00, 1),
('Sulu Pearl Cake', 'White Vanilla', 'Sulu Theme', '6 inch', 420.00, 1),
('Basilan Rubber Cake', 'Vanilla', 'Basilan Theme', '6 inch', 370.00, 1),
('Puerto Princesa', 'Mango', 'Palawan Theme', '6 inch', 410.00, 1),
('Coron Island Cake', 'Coconut', 'Coron Theme', '6 inch', 420.00, 1),
('El Nido Paradise', 'Coconut Mango', 'El Nido Theme', '6 inch', 450.00, 1),
('Subic Bay Cake', 'Vanilla', 'Subic Theme', '6 inch', 380.00, 1),
('Clark Air Cake', 'Vanilla', 'Clark Theme', '6 inch', 370.00, 1),
('Angeles City Cake', 'Sisig Flavor', 'Pampanga Theme', '6 inch', 390.00, 1),
('San Fernando Giant', 'Vanilla', 'Pampanga Theme', '8 inch', 400.00, 1),
('Bulacan Pastillas', 'Pastillas', 'Bulacan Theme', '6 inch', 380.00, 1),
('Laguna Buko Pie', 'Buko', 'Laguna Theme', '6 inch', 400.00, 1),
('Quezon Coconut Cake', 'Coconut', 'Quezon Theme', '6 inch', 390.00, 1),

-- Batch 901-950
('Cavite Bibingka Cake', 'Bibingka', 'Cavite Theme', '6 inch', 370.00, 1),
('Batangas Kapeng Cake', 'Barako Coffee', 'Batangas Theme', '6 inch', 400.00, 1),
('Rizal Antipolo Cake', 'Suman', 'Rizal Theme', '6 inch', 380.00, 1),
('Marinduque Moriones', 'Vanilla', 'Marinduque Theme', '6 inch', 390.00, 1),
('Mindoro Tamaraw', 'Chocolate', 'Mindoro Theme', '6 inch', 400.00, 1),
('Romblon Marble Cake', 'Marble', 'Romblon Theme', '6 inch', 380.00, 1),
('Masbate Rodeo Cake', 'Vanilla', 'Masbate Theme', '6 inch', 370.00, 1),
('Catanduanes Pili', 'Pili Nut', 'Catanduanes Theme', '6 inch', 410.00, 1),
('Sorsogon Lahar Cake', 'Chocolate', 'Sorsogon Theme', '6 inch', 380.00, 1),
('Albay Mayon Cake', 'Chocolate Lava', 'Albay Theme', '6 inch', 420.00, 1),
('Camarines Sur Cake', 'Pili', 'CamSur Theme', '6 inch', 400.00, 1),
('Camarines Norte', 'Coconut', 'CamNorte Theme', '6 inch', 380.00, 1),
('Aurora Baler Cake', 'Coconut', 'Aurora Theme', '6 inch', 390.00, 1),
('Nueva Ecija Rice', 'Rice', 'NE Theme', '6 inch', 350.00, 1),
('Tarlac Ube Cake', 'Ube', 'Tarlac Theme', '6 inch', 390.00, 1),
('Pangasinan Bangus', 'Vanilla', 'Pangasinan Theme', '6 inch', 370.00, 1),
('La Union Grapes', 'Grape', 'La Union Theme', '6 inch', 400.00, 1),
('Benguet Strawberry', 'Strawberry', 'Benguet Theme', '6 inch', 420.00, 1),
('Mountain Province', 'Vanilla', 'Mountain Theme', '6 inch', 380.00, 1),
('Ifugao Rice Terraces', 'Rice', 'Ifugao Theme', '6 inch', 390.00, 1),
('Kalinga Coffee Cake', 'Kalinga Coffee', 'Kalinga Theme', '6 inch', 410.00, 1),
('Apayao Honey Cake', 'Honey', 'Apayao Theme', '6 inch', 380.00, 1),
('Abra Weave Cake', 'Vanilla', 'Abra Theme', '6 inch', 370.00, 1),
('Ilocos Norte Empanada', 'Savory', 'Ilocos Theme', '6 inch', 360.00, 1),
('Ilocos Sur Vigan', 'Vanilla', 'Ilocos Theme', '6 inch', 370.00, 1),
('Cagayan Valley Rice', 'Rice', 'Cagayan Theme', '6 inch', 350.00, 1),
('Isabela Corn Cake', 'Corn', 'Isabela Theme', '6 inch', 360.00, 1),
('Nueva Vizcaya Citrus', 'Orange', 'NV Theme', '6 inch', 380.00, 1),
('Quirino Province Cake', 'Vanilla', 'Quirino Theme', '6 inch', 350.00, 1),
('Batanes Ivatan Cake', 'Vanilla', 'Batanes Theme', '6 inch', 400.00, 1),

-- Final Batch 951-1000
('Home Baker Special', 'Vanilla', 'Simple Buttercream', '6 inch', 300.00, 1),
('Neighborhood Favorite', 'Chocolate', 'Chocolate Frosting', '6 inch', 320.00, 1),
('Tindahan Classic', 'Mocha', 'Mocha Frosting', '6 inch', 330.00, 1),
('Suki Customer Cake', 'Ube', 'Ube Buttercream', '6 inch', 350.00, 1),
('Barangay Birthday', 'Vanilla', 'Colorful Sprinkles', '6 inch', 340.00, 1),
('Kapitbahay Special', 'Chocolate', 'Simple Ganache', '6 inch', 350.00, 1),
('Meryenda Time Cake', 'Vanilla', 'Light Cream', '6 inch', 300.00, 1),
('After School Treat', 'Chocolate', 'Chocolate Drip', '6 inch', 340.00, 1),
('Weekend Family Cake', 'Vanilla', 'Fresh Fruit', '8 inch', 380.00, 1),
('Sunday Dessert', 'Chocolate', 'Whipped Cream', '6 inch', 350.00, 1),
('Everyday Classic', 'Vanilla', 'Buttercream', '6 inch', 300.00, 1),
('Budget Friendly Cake', 'Vanilla', 'Simple Frosting', '6 inch', 300.00, 1),
('Student Special', 'Chocolate', 'Chocolate Frosting', '6 inch', 310.00, 1),
('Office Treat Cake', 'Mocha', 'Coffee Cream', '6 inch', 340.00, 1),
('Quick Celebration', 'Funfetti', 'Vanilla Buttercream', '6 inch', 330.00, 1),
('Last Minute Cake', 'Vanilla', 'Whipped Cream', '6 inch', 300.00, 1),
('Rush Order Special', 'Chocolate', 'Quick Ganache', '6 inch', 350.00, 1),
('Same Day Delivery', 'Vanilla', 'Simple Buttercream', '6 inch', 320.00, 1),
('Express Birthday', 'Funfetti', 'Rainbow Frosting', '6 inch', 340.00, 1),
('Instant Celebration', 'Chocolate Vanilla', 'Marble Frosting', '6 inch', 330.00, 1),

-- Multi-tier additions (1001-1010)
('Grand Debut Tower', 'Pink Vanilla', 'Rose Gold Fondant', '10 inch + 8 inch + 6 inch', 500.00, 1),
('Silver Anniversary', 'White Vanilla', 'Silver Fondant', '8 inch + 6 inch', 500.00, 1),
('Golden Anniversary', 'Vanilla', 'Gold Fondant', '8 inch + 6 inch', 500.00, 1),
('Diamond Wedding', 'White Vanilla', 'Crystal Decor', '10 inch + 8 inch', 500.00, 1),
('Pearl Anniversary', 'Vanilla', 'Pearl Accents', '8 inch + 6 inch', 490.00, 1),
('Ruby Wedding Cake', 'Red Velvet', 'Red Fondant', '8 inch + 6 inch', 500.00, 1),
('Sapphire Anniversary', 'Blue Vanilla', 'Blue Fondant', '8 inch + 6 inch', 500.00, 0),
('Emerald Wedding', 'Green Vanilla', 'Green Fondant', '8 inch + 6 inch', 490.00, 1),
('Crystal Wedding Tower', 'Vanilla', 'Crystal Sugar', '8 inch + 6 inch', 500.00, 1),
('Platinum Celebration', 'White Vanilla', 'Platinum Accents', '10 inch + 8 inch + 6 inch', 500.00, 1);

GO

-- Verify count
SELECT COUNT(*) AS TotalCakes FROM Cakes;
SELECT 
    CASE 
        WHEN size LIKE '%+%' THEN 'Multi-tier'
        ELSE 'Single-tier'
    END AS TierType,
    COUNT(*) AS Count
FROM Cakes
GROUP BY CASE WHEN size LIKE '%+%' THEN 'Multi-tier' ELSE 'Single-tier' END;

SELECT MIN(base_price) AS MinPrice, MAX(base_price) AS MaxPrice, AVG(base_price) AS AvgPrice FROM Cakes;
SELECT availability, COUNT(*) AS Count FROM Cakes GROUP BY availability;

PRINT '✅ 1000 Cakes inserted successfully!';
GO
